:PROPERTIES:
:ID:       31607183-1c72-462f-b733-88810487166a
:END:
#+title: brain
#+filetags: Biology:Neuroscience:

* References 

* Summary 



* Parts


** Cerebrum

At the top / front of your head
The largest part of the brain.

Cerebral cortex: the outer surface of the cerebrum. Very wrinkly, with 2 hemispheres
- Corpus callosum: connects the hemispheres

Hemisphers have 5 lobes each:
1. frontal
   - largest individual lobe
   - reasoning
   - voluntary movement
   - executive function
   - social convention
   - learning / recalling info
   
2. parietal (top)
3. temporal (side)
4. insular (inside)
5. occipital (back)


Thalamus:

Hypothalamus:

Hippocampus: Manages and stores memory


** Cerebellum


** Anterior Cingulate Cortex

The anterior cingulate cortex does *cost-benefit analysis*. When you consider doing an action, the level of dopamine in the ACC tells it how rewarding the action will be.

The norepinephrine level tracks the physical/mental/emotional cost of the action.

The ACC has basically *no dopamine transporters* 
- this means that the norepinephrine transporters pick up both norepinephrine and dopamine

But sertraline only inhibits the DAT, not the NET. So it has basically no effect on preserving DAT in the anterior cingulate cortex!

The locus coeruleus has the power to directly send norepinephrine to the anterior cingulate cortex

** Prefrontal Cortex
