:PROPERTIES:
:ID:       a550b3a8-8bc2-4a0c-91ea-1cd42cc1123e
:END:
#+title: reactance
#+filetags: :biology:spite:

* References

* Summary

Reactance is basically that thing that happens when someone tells you that you can't do something, and you go /screw you, I'm gonna do it./ 

It's basically like a /spite-drive/.

You get flooded with dopamine and adrenaline

* Impossible Things to Learn Later

There are a number of things that are generally considered impossible to learn later in life; they have a *critical window*.

Notice that these all have a kind of *intuition* that sits at the center of them. Daniel Kahneman looked at *System 1 v.s. System 2 thinking*, where System 1 is intuitive and System 2 is logical / calculating.

It takes a lot of energy to sit down and calculate things. Prodigies, native speakers, etc. don't rely on logically thinking through the rules of grammar, or chess; they've internalized them.

At the same time, there are plenty of things that become intuitive but we start by concretely thinking through --- for example, when learning your times tables: we don't calculate 2 * 2 = 4, past a certain age, but we do when we're first starting out; over time, it becomes ingrained, and we don't think about it. On the other hand, 3*19, would make most people pause and work it out explicitly; it's not internalized.

** Native-Like Accent

** Grandmaster Chess Ability



** Ambidexterity

** Perfect Pitch

** Echolocation
