:PROPERTIES:
:ID:       31607183-1c72-462f-b733-88810487166a
:END:
#+title: brain
#+filetags: :Biology:Neuroscience:

* References 

* Summary 



* Forebrain (Prosencephalon)

The rostral (forward-most) part of the brain (closest to the eyes)

** Telencephalon

This is the *cerebrum*. It's the *largest* part of the brain

*** Frontal Lobe

**** Prefrontal Cortex
:PROPERTIES:
:ID:       074d6d1e-c985-4f6b-bfb1-913650132597
:END:

Handles executive functions
Involved in math

***** Dorsolateral Prefrontal Cortex

=Perfect pitch:= This is hyperconnected to the auditory pathways in those with perfect pitch, allowing them to essentially look up the name of a note

=Focus:= In a focused state, the dlPFC maintains a *stable attractor network* by persistently firing across the *GluN2B-containing NMDA pathways* 

***** Orbitofrontal Prefrontal Cortex

**** Broca's Area

*** Parietal Lobe

Involved in math

**** Primary Somatosensory Cortex

**** Intraparietal Sulcus

*** Temporal Lobe

Auditory processing, memory, emotion

**** Wernicke's Area

Language comprehension

**** Hippocampus

*** Occipital Lobe

Visual info

**** Primary Visual Cortex

** Diencephalon

Sits between the telencephalon and mesencephalon

*** Basal Ganglia

Parkinson's 
Huntington's
*** Thalamus

When you hear a phone notification, the thalamus is activated and transmits data to the locus coeruleus in the hindbrain, to produce norepinephrine.

*** Hypothalamus
*** Subthalamus
* Midbrain (Mesencephalon)
** Tectum
The dorsal part of the midbrain

*** Superior Colliculi
*** Inferior Colliculi
** Tegmentum
The ventral part of the midbrain

*** Red Nucles
*** Periaqueductal Gray
*** Ventral Tegmental Area

A group of neurons on the floor of the tegmentum. This is where a lot of your dopamine is produced


** Cerebral Peduncles
* Hindbrain (Rhombencephalon)
** Metencephalon
*** Pons
**** Locus Coeruleus
:PROPERTIES:
:ID:       a619e39f-11a2-48eb-bc9e-1ee54b6fe11d
:END:

*Very small* (only 10k - 15k neurons), but very important
        - The brain's main source of [[id:2f5d927b-fbd8-4eb2-9c6a-005f78a1c2aa][norepinephrine]]


Glutamate causes phasic spikes

*** Cerebellum
** Myelencephalon
*** Medulla

Makes up the lower part of the brainstem



* Parts



** Cerebrum

At the top / front of your head
The largest part of the brain.

Cerebral cortex: the outer surface of the cerebrum. Very wrinkly, with 2 hemispheres
- Corpus callosum: connects the hemispheres

Hemisphers have 5 lobes each:
1. frontal
   - largest individual lobe
   - reasoning
   - voluntary movement
   - executive function
   - social convention
   - learning / recalling info
   
2. parietal (top)
3. temporal (side)
4. insular (inside)
5. occipital (back)


Thalamus:

Hypothalamus:

Hippocampus: Manages and stores memory


** Cerebellum


** Anterior Cingulate Cortex

The anterior cingulate cortex does *cost-benefit analysis*. When you consider doing an action, the level of dopamine in the ACC tells it how rewarding the action will be.

The norepinephrine level tracks the physical/mental/emotional cost of the action.

The ACC has basically *no dopamine transporters* 
- this means that the norepinephrine transporters pick up both norepinephrine and dopamine

But sertraline only inhibits the DAT, not the NET. So it has basically no effect on preserving DAT in the anterior cingulate cortex!

The locus coeruleus has the power to directly send norepinephrine to the anterior cingulate cortex

** Prefrontal Cortex

** Hippocampus

** Parietal Cortex

** Frontal Lobe
