:PROPERTIES:
:ID:       2b12abda-198b-4c2d-b9a7-70bc34901265
:END:
#+title: hormones
#+filetags: :biology:endocrine_system:

* References

* Summary

* [[Id:7d45e4a7-7be7-49ed-acf9-dc6495008741][Ghrelin]]


* Serotonin
:PROPERTIES:
:ID:       9d00dfdc-507a-46ab-9ffa-03a2d278837f
:END:

Made in the *Raphe nuclei*

GABA

Derived from the amino acid L-tyrptophan, which is converted into 5-HTP and then into serotonin (5-HT)

Serotonin is a kind of mollifier; it alters the *baseline voltage* of neurons, making them *less reactive* to stress.

Serotonin is converted into melatonin at night.


** Phasic Spike Suppression

Serotonin will *suppress phasic spikes*. The VTA has GABA neurons sitting next to it, that contain 5-HT_2C receptors. When serotonin binds to these, the GABA neurons fire, sending out chloride.
The chloride freezes the dopamine neurons.

In the prefrontal cortex, serotonin binds to 5-HT_2A receptors on the terminals where dopamine is released.

Serotonin receptors are located all throughout your body.

*Wellbutrin* is an NDRI as opposed to an SSRI
- ND stands for /norepinephrine and dopamine/
- instead of blocking serotonin reuptake, it blocks norepinephrine and dopamine reuptake.
- this is used in compination with an SSRI to balance out the inhibitted dopamine production.


** SSRIs

When you take an SSRI, it immediately targets the synaptic cleft. The presynaptic neuron is covered in a protein called SERT (serotonin transporter). 

SERT sucks used serotonin out of the cleft, to recycle it. SSRIs bind into the SERT protein, inhibiting it.
- the serotonin then pools inside of the synaptic cleft.

Activating the serotonin receptors in the gut triggers nausea

*Sertraline* is designed to inhibit the /dopamine transporter/ slightly.

*** Micro-Rewards

Though SSRIs end up inhibiting phasic dopamine spikes, if you focus on getting lots of tiny dopamine releases, instead of one big one, the SSRI won't necessarily be able to block that. 

You can use this to maintain focus throughout the day.

*** Cold Showers

Actually stimulate 250% dopamine

** 5-HT_1A Autoreceptors

When there's too much serotonin hanging around, these autoreceptors tell the neurons to *stop releasing more serotonin.* 

Over time, if you maintain high serotonin, the 5-HT_1A receptors will be dissolved and the effects of the higher serotonin will finally take hold.

** BDNF

Serotonin stimulates [[id:e3c3f1eb-4d17-4fe7-a37e-d05dda04b550][brain-derived neurotrophic factor]], which in turn stimulates neurogenesis in the hippocampus.

This in turn allows the DMN to change its focus to be less on negative rumination.

** GABA

*** Heroin

Heroin binds to the Mu-Opioid receptors, shutting down the GABA cells. This is what leads to terrible addiction --- you aren't able to suppress the phasic spikes at all, and you get a horriffying amount of dopamine.

DeltaFosB accumulates to critical levels /within weeks/ 


* [[id:125297de-c559-4e5f-83a5-d084f3cc2366][Dopamine]]

The VTA fires in response to *reward prediction errors* 
- when an outcome is better than expected
- when stimulus predicts an upcoming reward

You can spike DA without spiking NE
- if you learn a cue for a reward, then at the cue, you'll get DA, but since it's expected, not NE



* [[id:2f5d927b-fbd8-4eb2-9c6a-005f78a1c2aa][Norepinephrine]]

You can spike NE without spiking DA production
- novelty without reward (sudden flash of a blue square)
- unexpected uncertainty
- environmental changes
- high-intensity sensory shocks

However, because the PFC has few DATs, a phasic spike of NE will take up all of the NETs, leaving the dopamine 

Actually the PFC also has *low NETs* compared to subcortical regions like the thalamus, hypothalamus, and bed nucleus of the stria terminalis

Clearing NE in the PFC relies on diffusion into neighbouring extracellular spaces and uptake by astrocytic organic cation transporters.

* Epinephrine

Also called *adrenaline.* Made mainly by the adrenal glands on your [[id:8dada547-abdb-4c47-aa53-73d4e8d137e5][kidneys]]. During stress, the adrenal glands send epinephrine into your bloodstream, spiking your heart rate, dilating your airways and mobilizing glucose

* Acetylcholine

Made in the *nucleus basalis of Meynert* and the *pedunculopontine nucleus*. Derived from choline, which is combined with Acetyl-CoA.

It alters cellular permeability

When acetylcholine binds to nicotinic receptors in the brain, which actually makes you more focused.
- during mediation and N2 sleep, your brain is /actually highly focused!/

When it binds to muscarinic receptors in the body, it slows your heart rate, drops your blood pressure, and relaxes your muscles.

When it's released it slows your heart.

=Focus:= When you start focusing on something, the dorsolateral prefrontal cortex sends a signal to the nucleus basalis to make a phasic spike in acetylcholine

=Cortical:= High during focused periods, low during meditation and N2 sleep. In N3 sleep, acetylcholine is basically zero. Then in REM sleep it gets very high, due to the pons.

=Peripheral:= This acetylcholine is high during meditation, N2, N3 sleep, and low during REM sleep.

=No overload:= Unlike the dopamine system, you can't really overload the acetylcholine system.
- dopamine has a positive feedback loop, whereas acetylcholine has a negative one
- acetylcholinesterace is incredibly fast compared to dopamine transporters


** Paralysis

High levels of acetylcholine trigger paralysis

** Acetylcholinesterase (AChE)

Converts acetylcholine into choline and acetate. One of the *fastest enzymes* in the body. It destroys acetylcholine within *microseconds* 

*** Hypercholinergic State



** Nicotinic Receptors

When acetylcholine binds to nicotinic receptors on targetted neurons, it opens up sodium channels; the neurons' potentials become close to firing. This amplifies incoming info on the task at hand

*** Nicotine

When you smoke a cigarette, nicotine hits your brain in /7 seconds/. It binds to the nicotinic receptors in the VTA, sending out a phasic spike of dopamine.



** Hemicholinium

Blocks choline reuptake

** Vesamicol

Blocks VAChT

** Parasympathetic Nervous System

** Somatic Nervous System

** Sympathetic Nervous System

** Central Nervous System

Acetylcholine is produced from oligodendrocytes. This actually inhibits those oligodendrocyte progenitor cells from maturing into myelinating oligodendrocytes
- it activates Chrm1

The reason you don't want excess myelination is that it's essentially permanent; if you myelinate incorrect pathways, it's obviously not good; you'd lock in mistakes and random thoughts.

=LTP:= (Long-term potentiation) The acetylcholine essentially marks the pathways that you're training, for later myelination

When you sleep, your acetylcholine drops and the myelin gets produced

=Doom-scrolling:= When you spend all day in /moderate attention/, you sort of sit in the worst possible place with respect to myelination --- your acetylcholine never gets low enough to make mature oligodendrocytes.

*** Multiple Scelrosis





** Disease

*** Huntington's

Characterized by decrease in acetylcholine and GABA 

*** Alzheimer's

Treatment relies on AChE inhibitors, to boost remaining ACh

* Anandamide
