:PROPERTIES:
:ID:       e905726f-8605-4bfc-97e9-3faafe0393e1
:END:
#+title: singing
#+filetags: :biology:art:

* References

* Summary

Sound is longitudinal pressure wave. It contains areas of high density (compression) and low density (rarefaction)

When the glottis opens, air particles are pushed through, by subglottal pressure. The actual molecules themselves don't make it very far, and travel relatively slowly. What creates the sound is the molecules colliding with each other: the *collision energy* travels along

=Note:= The *mean free path* of air at atmospheric pressure is only about 68 nm. So air molecules are colliding all the time
- an average air molecule undergoes about *7B collisions / second* (7 \times 10^9 Hz)

The actual pressure waves produced by the voice are only about 0.1 Pa. But the standard atmospheric pressure is *101,325 Pa*.
- the fact that our ear is able to discern a 0.0001% change in pressure is absolutely insane.

The smallest sound a human can hear at 1000 Hz is about 20 \times 10^-6 Pa.
- that causes the eardrum to move 10^-11 m (!!!!) that's *smaller than the diameter of a hydrogen atom*. And we can hear it?!!?

* Air

** Subglottal Pressure

The diaphragm and intercostal muscles regulate the air flow. *Support* is essentially the condition of maintaining *constant subglottal pressure* as volume of air in the lungs decreases.

Subglottal pressure determines the loudness of the voice, by altering the amplitude of the 

As the pressure increases, 

** Maximum Flow Deceleration Rate

The slope of the glottal flow waveform as it falls back to zero.

Acoustic power is propertional to the square of MFDR; if the folds snap shut quickly, the glottal flow stops quickly

** Acoustic Radiation Pressure

The air pressure coming out of the mouth

$P_{a}_{r} \propto P_{s}^{2}$.

** Perceived Loudness

This is the sound pressure level

* Vocal Tract

** Lungs

** Trachea

A rigid tube made of cartilage rings. These are extremely sturdy and prevent your airway from collapsing inward when air gets pulled into the lungs, and the pressure in your trachea decreases.

** Subglottic Space

This sits right below the larynx. The air from the lungs pools here, while the vocal folds are closed.

Eventually the air pressure forces the folds open.

** Larynx

This contains all of the main pieces of your voice:

1. Vocal folds
2. Glottis
3. Epilaryngeal space

The larynx is a protective cage made up of cartilage, that sits on top of the trachea.

** Vocal Folds


The vocal folds actually aren't very thin; they're more like a block.

*** Glottis

The space between the vocal folds. This is initially shut, but air pressure from the subglottic space pushes it open from the bottom.

Since the folds have some depth to them, they open from the bottom to the top, which takes a bit of time.

Now, as the air passes through the glottis, the elasticity of the folds wants to push the glottis closed. But the column of air being pushed through them wants to keep it open.

This is where Bernoulli's principle comes into play

*** [[id:11a06f4c-fde1-45a9-b0fa-dd2477a19894][Bernoulli's Principle]]

The energy associated to a fluid in motion (like anything) is made up of kinetic and potential energy. The potential energy of the fluid corresponds to the /pressure/. So

$E = \dfrac{1}{2} \rho v^{2} + P$

If the energy is constant, Bernoulli's law says that increasing the velocity decreases the pressure. Inside the glottis things are a bit different.
- the above equation holds for *inviscid laminar incompressible flow* that *remains attached to the glottal wall* 
- in reality, vortices form as the glottis opens
- and flow separates from the wall: it becomes a *free jet* 
- air is actually compressible (but it doesn't really happen at the glottal pressures, so this isn't a big factor)

This is actually *a good thing* --- it allows the pressure inside the glottis to /decrease/, which leads to its closing.

Basically the reason the glottis closes is due to *friction*. The air touching the tissue of the vocal folds travels slower, because of the intermolecular forces between the folds and the air. This eventually causes the air at the boundary to /stop/.

But how does that work at the molecular level? Heat is really *disordered motion* --- it's not just kinetic energy; it's also about the direction.

When the fluid hits the vocal folds, the energy that goes into the folds gets converted into energy *in all directions* (this is "heat" in the vocal folds). So instead of having nice elastic scattering, where all of the energy goes into the wall, bounces off a molecule, which bounces off of another,... until it slows and comes right back, you instead get the initial energy into the wall broken into tiny bits in every direction, so the amount that comes back to the fluid is much less than originally went into the wall.

This is the molecular appearance of /heat./ So now the fluid has less energy to push against the wall. But the wall still has the same energy to push back (it didn't lose any energy; it gained a bit in all directions, but the energy into the fluid is still more or less the same). So the glottis starts to close again. 

Meanwhile, the further you get into the bulk of the fluid, the faster the air travels. 

Because the boundary air lost all of its energy, it can't hold the wall back, and the folds start to collapse inward. As it does this, the flow in the bulk gets ripped away from the boundary air, and becomes a *free jet* that isn't attached to the walls anymore.

The free jet then creates *vortices* and *turbulence*, introducing all kinds of complicated differential equation mess.

When the glottis opens, the energy of the air right at the beginning of the glottis is potential (pressure) energy, that gets converted into kinetic energy, as the air moves into the glottis. By Bernoulli, this decreases the pressure at the mouth of the glottis.

The closure of the glottis is often attributed to Bernoulli's principle... this is more-or-less /wrong/. Bernoulli's principle does play a role, but not a significant one, as we now know.

Bernoulli's principle says that in a fluid *with steady flow* the higher the velocity of the fluid, the lower the pressure.
- this is essentially /conservation of energy./ 

So for example, if air or water is accelerating (i.e. if a force is acting on it), it will drop the pressure. But this only works /once the fluid is already flowing/. 

When the glottis opens, the air that was blocked by it initially accelerates, but this is irrelevant, because the air /wasn't flowing/ just before then (because it was blocked by the closed glottis). So as the air passes through the glottis, it doesn't actually drop the pressure.

What does happen, is that the vocal folds are elastic and the *myoelastic forces try to force them closed*. This seems like it wouldn't work --- the subglottal pressure is able to force them open in the first place, so how could they possibly be strong enough to close back up?

The further the glottis opens, the more powerful the elastic restoring force. But it seems like the system should just reach equilibrium: the restoring force should balance with the outward pressure, and the glottis should remain partially open as the air passes through.

But note that momentum $p = dF/dt$. 

Then air from the lungs pools again, increasing the pressure until the folds open up again. This cycle produces an alternating wave of air, called the *glottal flow.* 

The glottal flow is what creates sound! Because of atmospheric pressure, there's always some air in our vocal tract already
- when the open glottis allows air through; it crashes into air molecules already sitting above the glottis, which then crash into the next layer of molecules, and so on, creating a *pressure wavefront*
- when the glottis closes, there are no new air molecules coming through, so the pressure right above the glottis decreases


**** Rarefaction

As the glottis closes and no new air is coming through, some of the air above the glottis continues moving forward, creating a rarefaction zone (lower pressure) above the glottis.

Now, air molecules aren't all traveling the same direction; there are always some of them are traveling backwards, towards the glottis. When the air gets cut off by the glottis, those air molecules moving backwards will actually move towards the glottis, which also contributes to the rarefaction.

=Note:= If the folds are open, the air after the glottis still crashes into the next bit of air, but there's no area of rarefaction, so instead of a wave with peaks and troughs, you just get a steady block of pressure, which doesn't correspond to sound (or really it's a kind shush or breath-like sound; white noise basically).

**** Bernoulli pt 2.

The rarefaction at the top of the glottis actually allows the vocal folds to close up *at the top*. So now you have the folds closing in both directions (from the bottom and from the top)

This allows the air to get *cut off even faster*.

**** Fourier Series

Fourier theory tells us that the sharper the edges on a periodic function, the more sine waves (i.e. the more overtones) you need to form it. 

When the glottis just closes from the bottom, you get a very slow cutoff of the air, and thus the rarefaction zone is produced smoothly: the pressure drops little by little, as the air is slowly closed off through the glottis.

But if you can clamp the glottis shut at the top and bottom, your pressure wave has a *sharp drop* --- it's basically a *sawtooth wave*! Which means that the sound that will be produced when you have a whole bunch of these sawtooth pieces will have *a ton of higher overtones*
- this is precisely how opera singers are able to make that operatic, resonant sound: they close the glottis from both the top and bottom, creating a sharp cutoff that corresponds to higher resonance.

But why doesn't everyone sound operatic all the time then?

The key is the /way the air column above the glottis moves/, leaving the rarefaction zone behind.
- if your throat is too tight, it blocks the air from moving quickly up the vocal tract
- instead, it moves slowly, the pressure doesn't drop as fast, and the upper glottis doesn't shut fast.


** Ventricular Folds

Also called the *false vocal folds.* 

** Epilaryngeal Space

Sits right on top of the larynx. You need it to act as a smooth transition between the vocal folds and the pharynx (which is just open air inside your throat)

When sound travels between materials with different impedances, a lot of energy reflects at the boundary between the media. This is because the two different media have *different densities and elasticities*.

If you start with loose, light molecules (low density, high elasticity) and go to tight heavy ones
- the inertia of the heavy molecules causes them to barely move, and the momentum is transferred backwards into the light medium (this is the reflection)

If you start with a dense, inelastic material and go to a light, elastic one
- the heavy molecules meet no resistance, and so they actually bulge out into the light material, causing a drop in pressure at the location the heavy molecules were initially
- unfortunately, the light molecules aren't able to take all of the energy of the heavy ones, so a lot of it gets reflected back
- think of a heavy car hitting a light one; the light car goes flying, but the heavy car also keeps moving, because only a bit of the energy was taken away.


*** Physics Derivation

Why does this happen? Well if we look at conservation of momentum:

Say the heavy molecule has speed $v_{0}_{}^{}^{M}$ and mass $M$ and the light one is /initially at rest/ and has mass $m$ and gets accelerated to velocity $v_f^m$_{}^{}. Then by conservation of momentum:

\[
M v^{M}_{0} = v_{f}^{M} M + v_{f}^{m} m
\]

Now use conservation of energy:

\[
m (v_{f}^{m} )^{2} + M (v_{f}^{M})^{2}= M (v_{0}^{M})^{2}
\]

We rewrite both equations to get
$M(v_{0}^{M} - v_{f}^{M}) = v_{f}^{m} m$
$m (v_{f}^{m})^{2} = M(v_{0}^{M} - v_{f}^{M})(v_{0}^{M} + v_{f}^{M})$
 
Yielding $v_{f}^{m} = v_{0}^{M} +v_{f}^{M}$; plugging into the conservation of momentum and rearranging gives

$v_{f}^{m} = \dfrac{2M v_{0}^{M}}{M + m}$

which shows that the final velocity of the smaller particle can never exceed $2 v_{0}^{M}$, and in fact decreases as $m$ decreases.


**** Relativity

By the way, close to light speed, this stops holding (this isn't relevant for sound waves, but it's just a cool fun fact). It turns out that if you use the relativistic versions of the equations, heavy molecules can transfer essentially all of their energy to lighter ones in a collision!

This is actually something that produces *cosmic ray air showers* in our upper atmosphere.

*** Acoustic Impedance Matching

So we need the epilaryngeal space to help us match the densities of the vocal folds and the pharynx; otherwise *sound will be lost through reflections.* 
- even if you get all of those nice resonances from the closing of the upper glottis, you won't be able to hear it if all of the sound gets reflected back down into the vocal folds.

One way around this it to just try to increase the amplitude / energy of the sound --- this is what untrained singers do

*** Acoustic Impedance

Acoustic impedance (Z) is acoustic pressure (\Delta P) divided by the *acoustic particle velocity* (u) and the cross-sectional area of the tube. 

\[
Z = \dfrac{\Delta P}{u A}
\]

=Pressure:= The acoustic pressure is the difference between the baseline pressure of the medium, and the local pressure making up that region of the sound wave; in other words, the difference of the bunching up of the molecules as the sound wave passes through them, from when they're left alone.

Why does the pressure change as you pass through different media? The pressure wave travels along as a macroscopic phenomenon, due to the molecule motion carried forward by  kinetic energy. Depending on the medium, it might be harder or easier to move molecules.

When the medium is dense, the molecules are tightly packed. They can't move very much at all, so as the energy passes through them, they stick together locally, giving a high pressure

In a low density medium, the molecules have a lot of room to move, and so as the energy passes through them, you only have a few molecules moving together at a time, until they crash into the next group, and those few ones move together, and so on. So the pressure is lower.

=Velocity:= But there are 3 different velocities of the sound:

1. Bulk flow velocity: the speed of the individual molecules traveling along the vocal tract
2. Wave velocity: the speed of the pressure wave (the speed of sound in the medium)
3. Acoustic particle velocity: the speed of the molecules oscillating back and forth as the pressure wave passes through them.

=Vocal folds:= High impedance

=Pharynx:= Low impedance: the cross sectional area is huge, and the pressure is much lower

=Epilaryngeal:= If we make the tube very narrow, we reduce the cross-sectional area, /increasing the impedance./ 


** Aryepiglottic Sphincter

This is a ring of muscle that sits on top of the vocal folds. They connect to the arytenoid cartilage at the back of your vocal folds, all the way up to the sides of the epiglottis (which is what closes when you swallow)

When you activate these muscles, you narrow the vocal tract at that point

=Sensation:= The feeling of closing the glottis is like when you hold your breath. But tightening the aryepiglottic sphincter feels like the sound is brightening; more pointed; you aren't changing the folds, you're just forcing the sound through a smaller hole
- it's that nasally sound in a duck's "quack quack" or a witch's cackle.


*** Impedance Matching

We use the sphincter to narrow the epilaryngeal space, increasing the impedance to *match the vocal folds.* This prevents us from losing energy in the transition from the folds to the epilarynx.

But what about going into the pharynx? There should still be a reflection problem since the impedance drops.

Well, when you use the aryepiglottic sphincter, it doesn't give you a harsh sudden narrowing into the pharynx; it's more tapered. As you travel along, and the tube widens, the impedance does still change, and you get mini reflections along the way, but they end up adding to less than if you just did a hard transition from the folds right into the unnarrowed pharynx.

*** Resonance and Amplification

Because the epilarynx is closed at one end (the vocal folds) and open at the other (the top of the sphincter), it's a *quarter wave resonator* --- this means it will *amplify* any sound whose wavelength is exactly *4 times the length of the tube*.

If you work out the calculation for the 2-3 cm long epilaryngeal tube, you get that it's about *3000 Hz* (!)
- so the epilaryngeal tube naturally amplifies the sound of the higher frequencies
- thus if you produce those higher frequencies with a sharp closure of the glottis, they'll actually get amplified in the epilaryngeal tube!

At the opening to the pharynx, the molecules hit by the sound wave get thrown into the pharynx due to the low impedance (this is called an *acoustic pressure node*). As we mentioned above, it's impossible for the light molecules in the pharynx to carry all of the energy of the pressure wave, so a bunch of it does reflect back (about 50% even in the best case scenario)
- still, this is much less than what happens in the case that you don't narrow the pharynx (which is something like 95% loss)

So if you aren't singing opera, and don't have those amplified 3000 Hz frequencies, you just end up with 50% of the sound you started with

But if you do have those 3000 Hz, look what happens:
- they get reflected back down the epilarynx, but then that means they get *amplified again!*
- and then they get reflected back down towards the pharynx, and amplified again
- this ends up creating an /immense sound/, not even remotely comparable to non-operadic singing

You very quickly reach equilibrium though, which is why the sound doesn't just get louder forever

** Pharynx

Goes from the top of your larynx to the back of your nose.

Highly muscular, allowing fine control

In opera we want to *widen the pharynx* (this is the famous /open throat/). We need a nice gradual taper along the pharynx, to make sure that the impedance mismatch doesn't destroy the sound.

*** Inferior/Middle Pharyngeal Constrictor Muscles

In speech, these are squeezed inward. In opera, we keep them widened.

This creates a large chamber that *amplifies lower frequencies* 

But we need this to give a /gentle taper/. So in fact, the inferior muscles can't just go completely slack. You have to figure out the perfect way to slowly loosen the muscle as you move upwards (this is one of the many reasons why opera is so hard)

By nature, the pharyngeal constrictors *all fire together*; they're meant to push food into the esophagus
- this is called *peristalsis* 

You need specific training to overcome this

**** Incipient Yawn

You practice the *very start of a yawn* --- where the lower throat opens, but the top doesn't

**** Semi-Occluded Vocal Tract



*** Infrahyoid Muscles

Your pharynx starts where the larynx stops. You can lengthen it by moving the larynx down. Lengthening a tube shifts its resonances lower, so this allows you to emphasize the low frequencies even more. But it also /bunches the higher frequencies closer/ 

Normally, your pharynx has resonances around 2500 Hz, 3000 Hz, and 3500 Hz. When you lengthen the pharynx, these regions coallesce into one big region
- so it actually improves the high frequencies /even more!/ 

The sternohyoid and sternothyoid muscles pull the larynx downward.

*** Velopharyngeal Closure

The *soft palate* or /velum/ sits between the pharynx and the nasal cavity. Opera singers will actually try to *completely seal off the nasal cavity* 

The levator veli palantini muscle contracts, lifting the soft palate and slamming it against the back of the throat.

This is very surprising, because in singing, you're often taught to activate /nasal resonance/. Turns out, there's *no such thing as nasal resonance* --- you're never actually meant to resonate the sound in your nasal cavity (if you do get the sound in there, the spongey tissue and hairs there will actually kill it; especially the high frequencies). When passing through the nasal cavity, the sound actually winds up /muffled/ 

The reason it /feels/ like it's in the nose, is because if you manage to get the higher frequencies into your mouth, they resonate the /hard palate,/ which then reverberates up into the nose.

*** Tongue Root

The back of the tongue actually sits inside the pharynx. In untrained singing, the tongue will fall backwards and close off the pharynx.

The genioglossus muscle moves the root of the tongue forward and down, away from the back wall of the throat

** Oral Cavity

*** Jaw

Opera singers drop the jaw *down and back*, rotating it at the TMJ (temporomandibular joint); this helps with that gentle taper: they keep space in the back of the throat into the mouth, and then out

The wider the mouth, the *higher the $F_1$ formant*

*** Tongue

Controls the *$F_{2}$ formant*
- moving the tongue forward brings F_2 down
- moving the tongue back brings F_2 up


*** Lips

The tip of the tongue and the lips are used for *articulation* 
- in order to formant match high notes, you essentially need to make the AH shape for /every vowel/
- you use the tip of the tongue and the lips to express the consonants

* Acoustic Inertance

$M = \rho L/A$
M is the inertance, L is the length of the tube, and A is the cross-sectional area

Narrowing the epilaryngeal tube increases the inertance.
When the air reaches the wide pharynx, the inertance drops



* Muscles

** Interarytenoid Muscles

Close the glottis

** Lateral Cricoarytenoid Muscles

Close the glottis

** Cricothyroid Muscle

Tilts the thyroid cartilage forward from the cricoid cartilage. This /increases tension/ on the vocal folds and /thins their mass/.

** Thyroarytenoid Muscles

* Resonance

** Helmholtz Resonator

Picture a glass bottle with a narrow neck and wide body. If you blow on the top, the Bernoulli principle says the pressure will drop there, and so air from above the bottle will fall into the neck
