:PROPERTIES:
:ID:       3208f36e-5a54-4bfd-8bd5-9465bd1e9405
:END:
#+title: working
#+filetags: :biology:body:

* References

* Summary

It's simply unreasonable to expect people to work at maximum capacity for 8 or even 6 hours a day. If you look at people at the top of their fields --- mathematicians, scientists, athletes, artists --- they don't really work more than 4 hours a day at full intensity

* Work Hours

** Poincare

Worked 10am - 12pm and 5pm - 7pm.

He viewed math as something that primarily happens in the background; in your subconscious. He would literally spend the rest of his day doing whatever he wanted: he went to the beach, read, walked, wrote letters, etc.

** Hardy

As much as I don't like a lot of his ideas in /A Mathematician's Apology/, I do generally agree with his perspective that 4 hours of creative work a day is the limit.

** Ignmar Bergman

Wrote 9am - 1pm and took an afternoon nap. Then for the rest of the day he read, took walks, and watched films

** Anders Ericsson

Practiced in 90min blocks for 3.5 hours

** Charles Darwin

Three 1.5 hour blocks

** Immanuel Kant

Was notoriously so consistent with his daily walks that citizens would set their watches by it.

Was woken by his servant at 4:45am every day. 

** Erdos

Was on amphetamines (Ritalin and Benzedrine) along with massive quantities of espresso that helped him focus. He also had a strong support network that handled all of his chores, managed his finances, wrote up all his papers, and gave him problems to work on.

He was able to hyper-focus on math, because everything else was handled for him.

** Newton

Newton tragically had serious mental health issues. He wouldn't eat or sleep, had few to no friends, was paranoid that everyone was trying to steal his work, never took walks. His most famous biography is called /Never at Rest./ 

Fascinatingly, though he's often upheld in contemporary narratives as a pure scientist, his obsession with work was actually highly based on religion --- part of his obsession came from the drive to understand God's plan and order to the universe, leading him to study things like physics, alchemy, and the bible.

** Grothendieck

Grothendieck also ended up with a number of mental health issues. He retreated from math by 1970 due in part to opposition with the IHES's military connections, but also ended up retreating from society at large. He cut off almost all ties with his former friends and colleagues, wrote apocalyptic work, went on long fasts that led him to severe malnourishment

** Bobby Fischer

Hyperfocused on chess up to the early 1970s, when he won the World Championship. Afterwards, he began a severe downward spiral, with worsening mental health reminiscent of Newton and Grothendieck.

He refused to defend his title in 1975, over disagreements with FIDE about the math conditions, and retreated from the public eye until 1992 when he won an unofficial match against Spassky in Yugoslavia, which led him to having to flee the US government (because Yugoslavia was under sanctions).

In the 1970s, he was highly religious, crediting his faith with his chess improvement. After leaving the Worldwide Church of God in 1977, he accused it of being Satanic. Near the end of his life he believed Catholicism was the only way of healing th world.

From the 1960s on, Fischer started making public antisemitic comments. Jan Hein Donner (a Dutch grandmaster) viewed Fischer as a fan of Hitler, whose mind was "completely cut off from reality."
 Post 1972 he became more and more vocally antisemitic and believed a number of conspiracy theories. He denied the Holocaust, believed the US was controlled by Jews. He consumed antisemitic literature like /The Secret World Government/.

Fischer was believed to have had a personality disorder.

** Nieztche

Had severe chronic illness. Worked from 5am to 11am until migraines forced him to stop. And then walked *for 7 hours!* on which he would continue to write. 

** John Stuart Mill

His dad controlled his life from a young age. He was woken at 5am every day. If he made mistakes in his morning work, he didn't get lunch. He wasn't allowed to have any friends.

He had a breakdown at age 20 and almost committed suicide.

** Tesla

Claimed to sleep only 2 hours a night and work 80-hour stretches. He had a nervous breakdown in 1881 in Budapest.

He also had OCD

** Euler

Worked with his children around him and in between domestic tasks.

Averaged 800 pages a year

He was able to increase his productivity after he went blind --- in fact, /most/ of his work is from that period. He employed scribes and his kids to write out his math and check it for consistency. So like Erdos, he had some of the publication tasks taken care of for him.

** Gauss

Gauss was heavily impacted by the death of his first wife, Johanna Osthoff in 1809, when she was 29, a month after giving birth to their third child.

Prior to Johanna's death, Gauss focused mainly on pure math, like number theory. In his diary we see a joy around mathematics and life. He wrote in an 1808 letter to Bolyai about how 

/The days go happily by in the uniform course of our domestic life: when the girl gets a new tooth or the boy learns some new words, then this is nearly as important as the discovery of a new star or of a new truth/ 
[Gauss: A Biographical Study; Death of Johanna and Second Marriage, W.K. Bühler. (1981)]

After Johanna's death, Gauss fell into chronic depression. He used exhausting, tedious, applied work to distract himself from his depression. He also became far more selective in what he chose to publish.

Gauss was a very grumpy and abrasive man, and was a jerk to people like Abel and Bolyai.

** James Joyce

Had intense agoraphobia and had serious eye problems. He spent decades in serious eye pain due to botched surgeries.

His daughter Lucia had severe schizophrenia, which stressed him out.

He ended up writing Finnegans Wake while lying on his stomach in bed, using crayons to make the text visible to his failing eyesight.  

** Percy Shelley

Experienced frequent hallucinations, paranoia, and melancholy. Three of his young children died, and his first wife committed suicide.

Like Newton, he would often forget to eat or sleep when composing

He wrote while walking miles through the Italian countryside, on whatever paper was available.

** John Keats

Keats' mother and brother died of tuberculosis, and Keats later got it as well. He had severe anxiety and depression, exacerbated by the fact that he couldn't afford to marry Fanny Brawne.

He was acutely aware that he was dying and was trying to complete as much as he could before he went.

** T.S. Eliot

Chronic anxiety and depression. He had a traumatic marriage with his first wife, Wivienne Haigh-Wood, who also suffered from severe mental and physical illness.

Eliot had a mental breakdown in 1921.

He worked as a clerk at Lloyds Bank in London and wrote in the evenings and on weekends. He became chronically exhausted. He actually wrote /The Waste Land/ while he was on *psychiatric leave* at a sanatorium in Switzerland. 

** Byron

Had a clubfoot, which brought him deep insecurity and an obsession with his appearance. He had severe mood swings and was likely bipolar. When he was manic, he would engage in furious boxing and fencing matches, swim for miles, and then write thousands of lines of things like Don Juan.

** Anthony Trollope

Woke at 5:30am every day and wrote 250 words / 15 minutes for 3 hours, before going to work at the Post Office. He wrote 47 novels.

His goal was to write 10 pages a day in the morning before work.

Trollope's process looked like this
- work out meticulous plot outlines for his work
- every day started with a 30 min warmup of reading and editing the previous day's work
- then start the 3 hour writing process
- on his long commutes in his job at the Post Office, he pre-wrote his dialogue and characters

Trollope would be content writing a dry boring version of a scene, as long as he got something down. 

** The Bronte Sisters

Death

* Attention Hogs

It's actually amazing how much low-effort dopamine sinks have been able to capitalize on our time and subjugate our creativity

Writers like Joyce and Trollope experienced significant boredom, loneliness, and exhaustion. 

Today, when we get stuck, our brain signals us to get a quick hit of dopamine through our phones. It's sort of like how today we have incredibly high-caloric foods that our bodies never evolved to deal with. So our brains and bodies signal us to interact with them in problematic ways. 

** Variable Rewards

Social media feeds cleverly use /variable rewards/
- you scroll because your brain tells you that you /might/ find something interesting.
- like a slot machine; you pull the lever because you might win.
- you check your phone because there might be a message.

This breaks up our attention into tiny little chunks; we have difficulty staying focused for extended periods before feeling the need to get a dopamine hit or check if we got a notification.

** Availability Paradox

Because past researchers had to wait a long time for correspondence, they had a lot of time to sit and think about the problem before they got a response. 

Today, the whole of research is at our fingertips, and so we easily fall down *rabbit holes*, and learn a lot of shallow material, rather than investing significant time understanding anything deeply.

Similarly, the time of this surface level research (or going off on irrelevant researc tangents) distracts us from sitting down and actually writing (this is something I really struggle with!)
- in other words, we focus more on *consumption* rather than *production*


** Euler

Euler was able to produce a tremendous amount of work amidst an equally tremendous amount of distraction. 

He constantly had work going on in the back of his mind; so he didn't need to sit down at a desk and warm up. This is similar to Trollope's prewriting.

He could seemingly snap his focus to whatever the moment demanded; he would be an attentive father and then when he had a free moment, immediately snap to continue his math.

This is actually reminiscent of Elijah Wood, who, on the set of the Lord of the Rings, could fall asleep instantly, and then wake up and immediately go right into a scene. And in fact this /is/ something Euler did as well!
He could apparently fall asleep almost instantly.
As soon as he got tired, he would just take a 10-20 min nap.

Supposedly, Euler was incredibly calm and happy all the time. He allegedly didn't even despair at going blind; he just accepted it as a new part of his life. He likely had *low cortisol* 


*** Default Mode Network

What happens when you let your *mind wander*

Your brain will actually *flush metabolic waste* during this time and *consolidate memory* 

* Sublimation

A psychology process where people transform socially unacceptable or painful impulses into creative/productive output.

* Capitalisme

Today the bureaucratic aspects of publishing take up a tremendous amount of time and lead to significant burnout --- self-promotion, travel, social media engagement, brand management, email, teaching, administrative duties, grant proposals, sitting on committees...

* Hypergraphia

An overwhelming compulsion to write


* Academia

Sadly, a lot of academic work is administrative, not research or teaching. 

secretary, travel agent, accountant, IT technician

* Focus

To focus, you need norepinephrine, along with dopamine in D1 to block distractions.

** Music

When you listen to unfamiliar, fast music, you get micro-prediction errors that stimulate dopamine and norepinephrine. But this is often too much --- it stimulates D2, rather than D1.

Something like Lofi is good because it's so predictable that phasic spikes don't occur, and blocks out background noise that could trigger phasic spikes.

** Action-First Dopamine Generation

* Deep Work

When you switch between tasks, a shadow of your first task stays stuck in your attention, called *attention residue.* 

** Multitasking

Because attention residue builds up, multitasking (which is really just incredibly quick context-switching) is *terrible for your focus.* 

* Journalism Method

Journalists need to be able to start working at a moment's notice

** Bookmarks

You leave yourself checkpoints / bookmarks that signal exactly what you should focus on the next time you start working.

Anthony Trollope actually did something similar

** Focus Trigger

** Deadlines

In journalism school, you're given intentionally messy data, and required to turn in a perfect 500-word story within, say 45min; even a minute over time results in a failing grade.

** Inverted Pyramid

=Lead:= 5W's

=Body:= Crucial details, quotes, context

=Tail:= Extra background info

** Beats


