:PROPERTIES:
:ID:       e905726f-8605-4bfc-97e9-3faafe0393e1
:END:
#+title: singing
#+filetags: :biology:art:

* References

* Summary

Sound is longitudinal pressure wave. It contains areas of high density (compression) and low density (rarefaction)

When the glottis opens, air particles are pushed through, by subglottal pressure. The actual molecules themselves don't make it very far, and travel relatively slowly. What creates the sound is the molecules colliding with each other: the *collision energy* travels along

=Note:= The *mean free path* of air at atmospheric pressure is only about 68 nm. So air molecules are colliding all the time
- an average air molecule undergoes about *7B collisions / second* (7 \times 10^9 Hz)

The actual pressure waves produced by the voice are only about 0.1 Pa. But the standard atmospheric pressure is *101,325 Pa*.
- the fact that our ear is able to discern a 0.0001% change in pressure is absolutely insane.

The smallest sound a human can hear at 1000 Hz is about 20 \times 10^-6 Pa.
- that causes the eardrum to move 10^-11 m (!!!!) that's *smaller than the diameter of a hydrogen atom*. And we can hear it?!!?

* Air

** Subglottal Pressure

The diaphragm and intercostal muscles regulate the air flow. *Support* is essentially the condition of maintaining *constant subglottal pressure* as volume of air in the lungs decreases.

Subglottal pressure determines the loudness of the voice, by altering the amplitude of the 

As the pressure increases, 

** Maximum Flow Deceleration Rate

The slope of the glottal flow waveform as it falls back to zero.

Acoustic power is propertional to the square of MFDR; if the folds snap shut quickly, the glottal flow stops quickly

** Acoustic Radiation Pressure

The air pressure coming out of the mouth

$P_{a}_{r} \propto P_{s}^{2}$.

** Perceived Loudness

This is the sound pressure level

* Vocal Tract

** Lungs

** Trachea

A rigid tube made of cartilage rings. These are extremely sturdy and prevent your airway from collapsing inward when air gets pulled into the lungs, and the pressure in your trachea decreases.

** Subglottic Space

This sits right below the larynx. The air from the lungs pools here, while the vocal folds are closed.

Eventually the air pressure forces the folds open.

** Larynx

This contains all of the main pieces of your voice:

1. Vocal folds
2. Glottis
3. Epilaryngeal space

The larynx is a protective cage made up of cartilage, that sits on top of the trachea.

** Vocal Folds


The vocal folds actually aren't very thin; they're more like a block.

*** Glottis

The space between the vocal folds. This is initially shut, but air pressure from the subglottic space pushes it open from the bottom.

Since the folds have some depth to them, they open from the bottom to the top, which takes a bit of time.

Now, as the air passes through the glottis, the elasticity of the folds wants to push the glottis closed. But the column of air being pushed through them wants to keep it open.

This is where Bernoulli's principle comes into play

*** Bernoulli's Principle

Bernoulli's principle says that the higher the velocity of a fluid, the lower the pressure.
- you can think of this as the molecules of the fluids rushing by, so there aren't as many of them moving transversal to the direction of the fluid flow

So when air passes through the glottis, it leaves a lower pressure in its wake, even though there's a /continuous stream of air/. This allows the vocal folds to get pushed together by their internal pressure and elasticity.

Then air from the lungs pools again, increasing the pressure until the folds open up again. This cycle produces an alternating wave of air, called the *glottal flow.* 

The glottal flow is what creates sound! Because of atmospheric pressure, there's always some air in our vocal tract already
- when the open glottis allows air through; it crashes into air molecules already sitting above the glottis, which then crash into the next layer of molecules, and so on, creating a *pressure wavefront*
- when the glottis closes, there are no new air molecules coming through, so the pressure right above the glottis decreases


**** Rarefaction

As the glottis closes and no new air is coming through, some of the air above the glottis continues moving forward, creating a rarefaction zone (lower pressure) above the glottis.

Now, air molecules aren't all traveling the same direction; there are always some of them are traveling backwards, towards the glottis. When the air gets cut off by the glottis, those air molecules moving backwards will actually move towards the glottis, which also contributes to the rarefaction.

=Note:= If the folds are open, the air after the glottis still crashes into the next bit of air, but there's no area of rarefaction, so instead of a wave with peaks and troughs, you just get a steady block of pressure, which doesn't correspond to sound (or really it's a kind shush or breath-like sound; white noise basically).

**** Bernoulli pt 2.

The rarefaction at the top of the glottis actually allows the vocal folds to close up *at the top*. So now you have the folds closing in both directions (from the bottom and from the top)

This allows the air to get *cut off even faster*.

**** Fourier Series

Fourier theory tells us that the sharper the edges on a periodic function, the more sine waves (i.e. the more overtones) you need to form it. 

When the glottis just closes from the bottom, you get a very slow cutoff of the air, and thus the rarefaction zone is produced smoothly: the pressure drops little by little, as the air is slowly closed off through the glottis.

But if you can clamp the glottis shut at the top and bottom, your pressure wave has a *sharp drop* --- it's basically a *sawtooth wave*! Which means that the sound that will be produced when you have a whole bunch of these sawtooth pieces will have *a ton of higher overtones*
- this is precisely how opera singers are able to make that operatic, resonant sound: they close the glottis from both the top and bottom, creating a sharp cutoff that corresponds to higher resonance.

But why doesn't everyone sound operatic all the time then?

The key is the /way the air column above the glottis moves/, leaving the rarefaction zone behind.
- if your throat is too tight, it blocks the air from moving quickly up the vocal tract
- instead, it moves slowly, the pressure doesn't drop as fast, and the upper glottis doesn't shut fast.

*** Epilaryngeal Space

Sits right on top of the larynx. You need it to act as a smooth transition between the vocal folds and the pharynx (which is just open air inside your throat)

When sound travels between materials with different impedances, a lot of energy reflects at the boundary between the media. This is because the two different media have *different densities and elasticities*.

If you start with loose, light molecules (low density, high elasticity) and go to tight heavy ones
- the inertia of the heavy molecules causes them to barely move, and the momentum is transferred backwards into the light medium (this is the reflection)

If you start with a dense, inelastic material and go to a light, elastic one
- the heavy molecules meet no resistance, and so they actually bulge out into the light material, causing a drop in pressure at the location the heavy molecules were initially
- unfortunately, the light molecules aren't able to take all of the energy of the heavy ones, so a lot of it gets reflected back
- think of a heavy car hitting a light one; the light car goes flying, but the heavy car also keeps moving, because only a bit of the energy was taken away.


**** Physics Derivation

Why does this happen? Well if we look at conservation of momentum:

Say the heavy molecule has speed $v_{0}_{}^{}^{M}$ and mass $M$ and the light one is /initially at rest/ and has mass $m$ and gets accelerated to velocity $v_f^m$_{}^{}. Then by conservation of momentum:

\[
M v^{M}_{0} = v_{f}^{M} M + v_{f}^{m} m
\]

Now use conservation of energy:

\[
m (v_{f}^{m} )^{2} + M (v_{f}^{M})^{2}= M (v_{0}^{M})^{2}
\]

We rewrite both equations to get
$M(v_{0}^{M} - v_{f}^{M}) = v_{f}^{m} m$
$m (v_{f}^{m})^{2} = M(v_{0}^{M} - v_{f}^{M})(v_{0}^{M} + v_{f}^{M})$
 
Yielding $v_{f}^{m} = v_{0}^{M} +v_{f}^{M}$; plugging into the conservation of momentum and rearranging gives

$v_{f}^{m} = \dfrac{2M v_{0}^{M}}{M + m}$

which shows that the final velocity of the smaller particle can never exceed $2 v_{0}^{M}$, and in fact decreases as $m$ decreases.


***** Relativity

By the way, close to light speed, this stops holding (this isn't relevant for sound waves, but it's just a cool fun fact). It turns out that if you use the relativistic versions of the equations, heavy molecules can transfer essentially all of their energy to lighter ones in a collision!

This is actually something that produces *cosmic ray air showers* in our upper atmosphere.

**** Acoustic Impedance Matching

So we need the epilaryngeal space to help us match the densities of the vocal folds and the pharynx; otherwise *sound will be lost through reflections.* 
- even if you get all of those nice resonances from the closing of the upper glottis, you won't be able to hear it if all of the sound gets reflected back down into the vocal folds.

One way around this it to just try to increase the amplitude / energy of the sound --- this is what untrained singers do

** Pharynx

Goes from the top of your larynx to the back of your nose.

Highly muscular, allowing fine control

** Oral Cavity



** Nasal Cavity

* Acoustic Inertance

$M = \rho L/A$
M is the inertance, L is the length of the tube, and A is the cross-sectional area

Narrowing the epilaryngeal tube increases the inertance.
When the air reaches the wide pharynx, the inertance drops



* Muscles

** Interarytenoid Muscles

Close the glottis

** Lateral Cricoarytenoid Muscles

Close the glottis

** Cricothyroid Muscle

Tilts the thyroid cartilage forward from the cricoid cartilage. This /increases tension/ on the vocal folds and /thins their mass/.

** Thyroarytenoid Muscles
