:PROPERTIES:
:ID:       0de438ab-edcf-499e-ac21-7ec0a384ec91
:END:
#+title: babies
#+filetags: :human:biology:

* References



* Summary

* Gaze aversion

When a baby turns away from you, it's a way to *calm their brain down* 

Faces are incredibly *data-intensive*, especially when you include things like talking. 

* Heavy sigh

When babies get excited, their breathing turns shallow. A deep sigh is often a way for them to reset their body. 

* Sudden emotional changes

Babies often jump between screaming and being super happy. They don't seem to hold onto emotions for very long. And neurologically, they /really can't!/ 

When an adult gets upset, we *ruminate* --- we reflect on what's got us so upset (and we might even continue to do things that make us upset --- looking at you, social media!)

Babies just live in the present, because their memory and complex thinking isn't too developed yet.

You can use this to your advantage if your baby's upset --- because they can't hold too much in their brain at once, if you provide them some new interesting thing to look at, the pain or frustration signals in their brain will get tossed out to make room for the new thing.

Similarly, adults can use logical thinking to help prevent ourselves from having a meltdown; a luxury babies lack.

But this should also be reassuring in some ways: because babies can't reason out /oh this is frustrating, but I guess it's not that bad/, they pretty much always react with the *same level of upset* to anything from a minor inconvenience to actual pain. So usually, a baby's screaming doesn't actually mean that something horrible is happening.

* Drooling

I've noticed that babies will drool a lot more when they're happy or focused. It's because their brains don't have the capacity to handle focusing on the matter at hand, and preventing drool from escaping!

Swallowing is a pretty complicated motor skill (as you'll notice if you ever try to feed a baby)

=Saliva:= Babies will produce more saliva as they age to both help with teething (soothing the gums), and to help with digestion (so they can eat solid foods)

=Happiness:= When a baby is happy, their salivary glands actually get stimulated to produce more saliva

* Fake cough

Babies love to do this little fake cough --- it will even make them laugh!

It's about cause-and-effect. You can never overestimate how smart a baby is --- they're often doing the fake cough *specifically to get your attention*. This is why they start laughing sometimes when you give them attention after they cough.

* Memory

=6-8 months:= Their memory is only about *one week* (maybe two).

* Mouth

The mouth contains the *highest concentration of nerve endings*. 

For babies, a huge portion of their brains are dedicated to processing info from the mouth

Babies stick things in their mouths to figure out what they are and what properties they have. Once we develop fine motor skills and better memories, we can just recall what things are without having to stick them in our mouths to find out.

=Antibodies:= From 4 - 18 months babies are still protected by *material antibodies* from the placenta during pregnancy and through breast milk. This helps neutralize microbes and allows the baby's body to safely practice fighting back against germs.

=Outside:= If you think about human history, most of our time has been spent outside. So babies have spent thousands and thousands of years sticking rocks, sticks, soil, leaves, etc. into their mouths. These things are considered /dirty/, but they aren't actually dangerous

=Sanitizing:= Fascinatingly, the actual dangerous pathogens are usually produced by things that humans do, not by things found in nature. For example, 

        1. Things touched by lots of people like restaurant highchairs (and so picking up large amounts of any pathogens they carry)
        2. Baby bottles, items used for formula (milk can breed dangerous bacteria in plastic at room temperature within a few hours)
        3. Toys that touch raw meat, pets, or someone who's sick
