:PROPERTIES:
:ID:       ed58971e-8536-48cb-a0c1-0630a8212dee
:END:
#+title: ocd
#+filetags: :biology:brain:psychology:

* References

* Summary

Anxiety is mainly due to the over-activation of the amygdala.

OCD has to do with the *cortico-striato-thalamo-cortical circuit.* 


* CSTC Loop

A loop of three brain regions:

1. Orbitofrontal cortex (OFC)
2. Caudate nucleus
3. Thalamus

The OFC generates intrusive thoughts and worries about things like not being clean.

The caudate nucleus is what *discards irrelevant worries.* In OCD, this part of the brain malfunctions.

The thalamus sounds the alarm when a thought gets past the caudate nucleus. It sends a signal back to the OFC.

This loop is the /obsession./ 

The compulsion is your brain trying to break the loop

** Caudate Nucleus

Heavily dominated by inhibitory serotonin receptors. These receptors don't activate unless there's a *ton of serotonin* 

*** Washing Hands

Typically when your hands feel dirty, the sensation of washing them sends an "all clear" signal to the caudate nucleus, which then closes the gate on the orbifrontal cortex signals.



* Avoidance Loop

Once the avoidance happens, you get a small phasic spike of dopamine, which influences DeltaFosB
