:PROPERTIES:
:ID:       6fd70e13-1ba8-4a2e-84b5-d3d3a5846d88
:END:
#+title: sleep
#+filetags: :biology:neurosci

* References


* Summary

* Interstitial Space

The fluid-filled gaps between neurons.

Astrocytes have $\alpha_{1}$ receptors that norepinephrine binds to, triggering calcium ion release. This causes the astrocytes to swell as they absorb more water, causing the narrowing of the interstitial space.

* Meditation

Meditation can actually mimic N1 sleep.
- intense \theta waves are generated in the prefrontal cortex

The vagus nerve is stimulated by slowed breathing. The vagus nerve mainly sends signals up to the brain, to the *nucleus tractus solitarius.* The NTS then sends inhibitory signals to the locus coeruleus. It also sends excitatory signals to the nucleus basalis and the pedunculopontine nucleus.

The vagus nerve also controls the adrenal glands.

* Stages of Sleep

** NREM Sleep

*** N1

[[id:d6bb9e1b-4d4c-4728-a0a5-656d048fb7ad][Norepinephrine]] begins to drop, expanding the interstitial space.

Theta waves

*** N2

K-complexes (large single delta waves)

sleep spindles

Blood volume drops, creating a low pressure environment that pulls in [[id:05efb201-93e2-440f-9c10-704d35b960ea][cerebrospinal fluid]].

*** N3

** REM Sleep

* Default Mode Network

Similar to sleep, it clears metabolic waste and consolidates memory.
The DMN is a network of brain regions that are active during mind-wandering.

Alpha and beta waves

During DMN, you have high levels of norepinephrine, which keeps the interstitial space in the brain narrow. So [[id:05efb201-93e2-440f-9c10-704d35b960ea][cerebrospinal fluid]] can't flow deep into the tissue. Some waste clearance does occur, but not much compared to during sleep.


* Circadian Rhythm

Our bodies have two clocks:
1. The SCN
2. The peripheral clocks (individual organs and tissues)

** Suprachiasmatic nucleus (SCN)

Part of the hypothalmus. Regulates sleep cycles.

Highly sensitive to light and neurological activity

The SCN sends hormonal and temperature signals to the peripheral clocks

The SCN can adjust its sleep-wake schedule within 1-2 days

*** Circadian Alterness Signal

The SCN manages this signal, which fluctuates throughout the day.
This dips around 1-4pm: the *post-prandial dip*

**** Post-Prandial Dip

Most people get sleepy in the early afternoon, between *1pm and 4pm*




** Peripheral Clocks

Adjust their sleep-wake schedule after *5-8 days*

*** Pancreas and Liver

Their clocks determine insulin production
- if they think it's night, even though you're wide awake, and you eat a meal, your pancreas won't secrete enough insulin and your liver will remain in glucose-production

* Core Body Temperature

Reaches minimum 2 hours before you wake

* Sleep Drive

Accumulation of adenosine in the brain builds up every waking hour


* Sleep Types

Sleep clears away adenosine

It also consolidates memories

** 20min Naps

** 90min Naps

** Prolactin

In biphasic sleep, in the period between the two sleeps (called *the Watch*), there are high levels of prolactin

During the Watch, avoid using your phone or anything that
1. Triggers unpredictable dopamine (notifications, news updates, social feeds)
2. Suppresses melatonin (blue light)





* Zeitgeber

Environmental cues that help your body synchronize its biological clock

** Exercise

Spikes cortisol, which drives up core body temperature and processsing speed

* Caffeine
