:PROPERTIES:
:ID:       2b12abda-198b-4c2d-b9a7-70bc34901265
:END:
#+title: hormones
#+filetags: :biology:endocrine_system:

* References

* Summary

* Serotonin
:PROPERTIES:
:ID:       9d00dfdc-507a-46ab-9ffa-03a2d278837f
:END:

Made in the *Raphe nuclei*

GABA

Derived from the amino acid L-tyrptophan, which is converted into 5-HTP and then into serotonin (5-HT)

Serotonin is a kind of mollifier; it alters the *baseline voltage* of neurons, making them *less reactive* to stress.

Serotonin is converted into melatonin at night.


** Phasic Spike Suppression

Serotonin will *suppress phasic spikes*. The VTA has GABA neurons sitting next to it, that contain 5-HT_2C receptors. When serotonin binds to these, the GABA neurons fire, sending out chloride.
The chloride freezes the dopamine neurons.

In the prefrontal cortex, serotonin binds to 5-HT_2A receptors on the terminals where dopamine is released.

Serotonin receptors are located all throughout your body.

*Wellbutrin* is an NDRI as opposed to an SSRI
- ND stands for /norepinephrine and dopamine/
- instead of blocking serotonin reuptake, it blocks norepinephrine and dopamine reuptake.
- this is used in compination with an SSRI to balance out the inhibitted dopamine production.


** SSRIs

When you take an SSRI, it immediately targets the synaptic cleft. The presynaptic neuron is covered in a protein called SERT (serotonin transporter). 

SERT sucks used serotonin out of the cleft, to recycle it. SSRIs bind into the SERT protein, inhibiting it.
- the serotonin then pools inside of the synaptic cleft.

Activating the serotonin receptors in the gut triggers nausea

*Sertraline* is designed to inhibit the /dopamine transporter/ slightly.

*** Micro-Rewards

Though SSRIs end up inhibiting phasic dopamine spikes, if you focus on getting lots of tiny dopamine releases, instead of one big one, the SSRI won't necessarily be able to block that. 

You can use this to maintain focus throughout the day.

*** Cold Showers

Actually stimulate 250% dopamine

** 5-HT_1A Autoreceptors

When there's too much serotonin hanging around, these autoreceptors tell the neurons to *stop releasing more serotonin.* 

Over time, if you maintain high serotonin, the 5-HT_1A receptors will be dissolved and the effects of the higher serotonin will finally take hold.

** BDNF

Serotonin stimulates [[id:e3c3f1eb-4d17-4fe7-a37e-d05dda04b550][brain-derived neurotrophic factor]], which in turn stimulates neurogenesis in the hippocampus.

This in turn allows the DMN to change its focus to be less on negative rumination.

** GABA

*** Heroin

Heroin binds to the Mu-Opioid receptors, shutting down the GABA cells. This is what leads to terrible addiction --- you aren't able to suppress the phasic spikes at all, and you get a horriffying amount of dopamine.

DeltaFosB accumulates to critical levels /within weeks/ 

* Dopamine

Produced in the *substantia nigra*  and the *ventral tegmental area.* Derived from the amino acid [[id:d35da251-a7a9-4987-82dd-9ca708edd67b][tyrosine]], converted into L-DOPA, and then into dopamine.

Dopamine is actually then used to make norepinephrine!

Dopamine modulates neural plasticity

Dopamine fires whenever your brain detects something *new, unexpected, or potentially rewarding.* For example, when you get a text notification.

Dopamine binds to G-protein coupled receptors (GPCRs) on the dendrites of prefrontal cortex neurons.
- binds to D1 receptors on non-essential neurons.
This activates potassium and sodium ions to lower the voltage of the non-essential neurons.
- this makes it harder for those neurons to fire.

Dopamine acts as an off-switch for *prolactin*.
- when dopamine is suppressed, prolactin increases, leading to fatigue, muscle weakness, bloating

** Calcium

Intense exercise like HIIT forces calcium ions into your brain's movement and reward pathways, which causes dopaminee vesicles to release their contents. 

** Cold Showers

Instead of a phasic spike, cold showers actually trigger prolonged tonic baseline dopamine by *250% for 3 - 4 hours*

Your skin has thermal sensors called A-delta and C nerve fibers, which have TRPM8 channels. When you step into cold water, the channels open, sending out a ton of calcium and sodium ions.

The ions first go to the locus coeruleus, causing 530% norepinephrine.
- this spikes blood pressure
- drops fatigue
- causes the gasp reflex

The LC sends signals to the ventral tegmental area and nucleus accumbens. The norepinephrine binds to the alpha-1 adrenergic receptors in the VTA, forcing their calcium channels open, causing the vesicles to dump a continuous flow of dopamine.

You don't need to use water, but water is *25 \times more thermally conductive than air*, so it strips your heat tremendously quickly.

Your *face, forehead, and neck* contain the highest density of cold-shock receptors

You need to stay in cold water for *2 - 3 minutes* 

*** Thermal Glow

When you're done, your skin looks flushed and you start to feel an intense warmth from your core

*** Autonomic Gasp Reflex

I just tried it out; it's pretty crazy how immediate it is; reflexes are fascinating to behold.

When you stick your face in cold water (I looked into the shower head while it was on cold), your chest muscles and diaphragm involuntarily contract. It becomes extremely difficult to try to take a breath, because your body is specifically trying to prevent you from inhaling cold water (it thinks you're drowning)

** Tonic Dopamine

When you are focusing on a task, your midbrain releases a slow steady stream of *tonic dopamine*. 
- it binds to the D1 receptors and helps silence the noise of irrelevant neurons.


** Phasic Spikes

When a sudden unexpected event happens, like a text message, the ventral tegmental area creates a /burst/ of dopamine, called a phasic spike.

This is too much dopamine for the D1 receptors to handle, so the excess dopamine binds to D2 and D3 receptors.

D2 receptors lower the threshold for neurons to fire
- this makes everything more distracting

When D2 receptors get hit, the ion channels of your current task pathway get flushed.

*** Down-regulation

When you get consistent phasic spikes, your body will actually *lower your baseline dopamine*, to try to prevent you from overwhelming D1 so much.

This leads you to an ADHD-like baseline, where your baseline is constantly bored and understimulated

*** Addictive Apps
:PROPERTIES:
:ID:       fd291087-2f1d-4eeb-ab0f-00f9279cdbb0
:END:

These are specifically designed to create phasic spikes.

They keep you guessing as to whether you're going to see something interesting or not (what will be on my feed today?)
- by destroying predictability, they keep phasic responses

Dopamine doesn't care about what a reward is, as long as it's *better or more novel than expected.* 

They remove pagination, so there's no natural stopping point.

Videos that succeed on the algorithm are those which deliver stimulation within the /first 3 seconds/ --- this makes them generate a phasic spike before your prefrontal cortex can determine whether it's worth paying attention to the video

Apps will often *delay notifications* and send you them at random times, to decrease predictability

*** Anger and Outrage

Anger can actually create *some of the largest phasic spikes*. The evolutionary explanation is that we get *angry at threats*, and we need phasic spikes to divert our attention towards those threats.

This is why outrage content is so effective as propaganda and click-bait

It's particularly problematic when it comes to SSRIs
- because your phasic spikes are surpressed by serotonin, negaive feelings like anger are some of the only things that have high enough spikes to break through.


** Willpower

Willpower is heavily determined by dopamine

** Boredom

Being bored is actually *extremely important* to make sure that your dopamine receptors are kept healthy.

Your VTA stops firing phasic spikes.you brain slowly increases the sensitivity and density of your D1 receptors.

During these intentional boredom phases you should *just daydream* 
- just lie down and stare at the ceiling or sky, and let thoughts come to you
- drink some tea while staring outside

** Yerkes-Dodson Law

If baseline dopamine and norepinephrine are too low, the brain is understimulated and constantly looks for stimulation. This is correlated with ADHD.

ADHD meds like Adderall or Ritalin bump up baseline dopamine and norepinephrine.

If you have too much dopamine and norepinephrine, you become hyper-vigilant. 

** Addiction

Addiction is controlled by the *mesolimbic dopamine system* 

Whenever you get a phasic spike, the transcriptor protein DeltaFosB turns on in the nucleus accumbens.

Unlike most proteins, DeltaFosB lasts for weeks or months. Having a lot of DeltaFosB causes your brain to build more dendritic spines

** Dopamine Transporters

The recyclers of dopamine.

There are *essentially no dopamine transporters in the anterior cingulate cortex or prefrontal cortex* 

** Medication

*** Metylphenidate

Things like Ritalin/Concerta

Blocks DAT

*** Amphetamines

Like Adderall/Vyvanse

Causes your neurons to release more dopamine

* Norepinephrine
:PROPERTIES:
:ID:       d6bb9e1b-4d4c-4728-a0a5-656d048fb7ad
:END:

Also called *noradrenaline.* Made mainly inside the brain, by the neurons called the *locus coeruleus.* It has influence over your blood pressure.

Norepinephrine keeps your brain alert and vigilant. The only time you have basically no norepinephrine is when you're sleeping; it drops to its lowest point during REM sleep.
- norepinephrine has to do with *external awareness*
- this is why it drops in sleep
- whereas acetylcholine is focused more internally, and so rises during REM

The locus coeruleus is packed with *adenosine $A_1$ receptors*. When [[id:d55a0d14-1826-4e49-a2a5-b08773e13c74][ATP]] breaks down, the released adenosine bonds to the A_1 receptors, and causes the neurons to hyperpolarize (drop in voltage)
- this slows down their firing rate, suppressing the release of norepinephrine

Astrocytes have $\alpha_{1}$ adrenergic receptors which norepinephrine binds to, causing the release of calcium ions inside of the astrocytes. The extra calcium ions, causes the astrocytes to absorb more water, causing the cells to expand and narrowing the interstitial space.

Norepinephrine also binds to $\alpha$-2A receptors on cortical neurons. 
- this inhibits cyclic AMP, causing the HCN channels to close, preventing electrical leakage, and amplifying the neurons' signals.


** NET

Norepinephrine transporters are the recycler of norepinephrine

* Epinephrine

Also called *adrenaline.* Made mainly by the adrenal glands on your [[id:8dada547-abdb-4c47-aa53-73d4e8d137e5][kidneys]]. During stress, the adrenal glands send epinephrine into your bloodstream, spiking your heart rate, dilating your airways and mobilizing glucose

* Acetylcholine

Made in the *nucleus basalis of Meynert* and the *pedunculopontine nucleus*. Derived from choline, which is combined with Acetyl-CoA.

It alters cellular permeability

When acetylcholine binds to nicotinic receptors in the brain, which actually makes you more focused.
- during mediation and N2 sleep, your brain is /actually highly focused!/

When it binds to muscarinic receptors in the body, it slows your heart rate, drops your blood pressure, and relaxes your muscles.

When it's released it slows your heart.

=Focus:= When you start focusing on something, the dorsolateral prefrontal cortex sends a signal to the nucleus basalis to make a phasic spike in acetylcholine

=Cortical:= High during focused periods, low during meditation and N2 sleep. In N3 sleep, acetylcholine is basically zero. Then in REM sleep it gets very high, due to the pons.

=Peripheral:= This acetylcholine is high during meditation, N2, N3 sleep, and low during REM sleep.

=No overload:= Unlike the dopamine system, you can't really overload the acetylcholine system.
- dopamine has a positive feedback loop, whereas acetylcholine has a negative one
- acetylcholinesterace is incredibly fast compared to dopamine transporters


** Paralysis

High levels of acetylcholine trigger paralysis

** Acetylcholinesterase (AChE)

Converts acetylcholine into choline and acetate. One of the *fastest enzymes* in the body. It destroys acetylcholine within *microseconds* 

*** Hypercholinergic State



** Nicotinic Receptors

When acetylcholine binds to nicotinic receptors on targetted neurons, it opens up sodium channels; the neurons' potentials become close to firing. This amplifies incoming info on the task at hand

*** Nicotine

When you smoke a cigarette, nicotine hits your brain in /7 seconds/. It binds to the nicotinic receptors in the VTA, sending out a phasic spike of dopamine.



** Hemicholinium

Blocks choline reuptake

** Vesamicol

Blocks VAChT

** Parasympathetic Nervous System

** Somatic Nervous System

** Sympathetic Nervous System

** Central Nervous System

Acetylcholine is produced from oligodendrocytes. This actually inhibits those oligodendrocyte progenitor cells from maturing into myelinating oligodendrocytes
- it activates Chrm1

The reason you don't want excess myelination is that it's essentially permanent; if you myelinate incorrect pathways, it's obviously not good; you'd lock in mistakes and random thoughts.

=LTP:= (Long-term potentiation) The acetylcholine essentially marks the pathways that you're training, for later myelination

When you sleep, your acetylcholine drops and the myelin gets produced

=Doom-scrolling:= When you spend all day in /moderate attention/, you sort of sit in the worst possible place with respect to myelination --- your acetylcholine never gets low enough to make mature oligodendrocytes.

*** Multiple Scelrosis





** Disease

*** Huntington's

Characterized by decrease in acetylcholine and GABA 

*** Alzheimer's

Treatment relies on AChE inhibitors, to boost remaining ACh
