:PROPERTIES:
:ID:       4ada6ef3-b80f-40ae-bf1e-1b9345577499
:END:
#+title: haskell
#+filetags: :comsci:language

* References


* Summary

Functional language

Haskell *doesn't have variables* in the sense of an imperative language
All "variables" are really explicit values that we give a name
- you aren't allowed to actually vary the value; every "variable" is a constant

This is actually *fantastic for optimization*
- compilers can optimize around the fact that all variables are constant
- for ex. you can replace all occurances of a certain variable name by a pointer to a single shared memory layout
       - ordinarily, if you did that for a non-constant variable, you'd risk the memory address being overwritten with different values as you change the scope

* Commands

** The Prelude

The functions that haskell natively has, before you import anything

*** Reshapers

**** foldr

#+begin_src haskell
foldr :: (a -> b -> b) -> b -> [a] -> b
#+end_src
=(a -> b -> b)= is the kind of shape that a node =(:)= has.
So we can write
#+begin_src 
foldr (:) z [1,2,3]
#+end_src
to replace


**** map

Applies a function elementwise to a list

#+begin_src haskell
map :: (a -> b) -> [a] -> [b]
#+end_src

**** concatMap

Applies a function f to each element in a list, giving you a list of lists.
Then it concatenates the nested list into a single list

#+begin_src haskell
map :: (a -> [b]) -> [a] -> [b]
#+end_src

**** filter

Evaluates a predicate function against each item in a list.
If the predicate returns true, the item stays, if false, it's dropped

#+begin_src haskell
(a -> Bool) -> [a] -> [a]
#+end_src

*** Folds

Basically these things take a list and replace all of the cons operators =(:)= with a specified function f, and replace the empty list =[ ]=, with a base-case z

**** foldr

Processes a list from right to left
- it computes f_1(f_2(f_3(z)))

#+begin_src haskell
(a -> b -> b) -> b -> [a] -> b
#+end_src
The first object is f
- we think of it as a list of functions, indexed by elements in our list
The second is z
The third is your list

Basically =f z [1,2,3]= becomes
f_1(f_2(f_3(z)))

So basically, it allows you to evaluate a composition of functions f_i :: b \to b on a fixed element z

Note: =foldr= is computed lazily
- if it can return without having to compute the nested compositions, it will

**** foldl / foldl'

Processes a list from left to right
- basically it wraps composition in the opposite way

#+begin_src haskell
(b -> a -> b) -> b -> [a] -> b
#+end_src

The first object is g
- we think of it again as a list of functions g_i = g(-,i) : b \to b
The second element is the base case
The third is the list

We get
g(g(g(z,1),2),3) = g_3(g_2(g_1(z)))

Note: Haskell's laziness treats this a little weird
- it will skip over g_1(z), leaving it unevaluated (we call this a *thunk*)
- then it'll do the same at g_2, and so on, until it gets to the end
- only then will it try to evaluate the whole thing
- because of this, you can actually run out of memory, since it'll leaving these thunks behind

Note: =foldl'= is usually better, because it evaluates at each step, instead of combining a bunch of unexecuted lazy expressions

*** Linkers and Slicers

**** zip

Takes two lists and locks them together into a list of tuples
- if one list is shorter than the other, it truncates at the shortest length

#+begin_src haskell
[a] -> [b] -> [(a,b)]
#+end_src

**** zipWith

Takes two lists, matches them index-by-index and applies a combining function

#+begin_src haskell
zipWith :: (a -> b -> c) -> [a] -> [b] -> [c]
#+end_src

**** replicate

Creates a list where every element has the same value

#+begin_src haskell
replicate :: Int -> a -> [a]
#+end_src


**** take / drop

=take n= grabs the first n elements of a list and drops the rest
=drop n= drops the first n elements from the list and returns the rest

#+begin_src haskell
Int -> [a] -> [a]
#+end_src

*** Combinations

**** Function composition

#+begin_src haskell
(b -> c) -> (a -> b) -> a -> c
#+end_src

**** Evaluation on a value

#+begin_src haskell
(a - > b) -> a -> b
#+end_src






* Compiler

Haskell's compiler is the *Glasgow Haskell Compiler* (GHC)

We can alter its behaviour using a *language pragma*:
={-# LANGUAGE [option] #-}=

#+begin_src haskell
{-# LANGUAGE OverloadedStrings #-}
#+end_src

This tells GHC to treat strings as arrays of bytes, as opposed to inefficient linked lists of characters.


* Types

** Word64

Unsigned 64-bit integer

** data

*** Sum Types

#+begin_src haskell
data sumTypeName
  = constructor1 Type1
  | constructor2 Type2
  deriving (Show, Eq)
#+end_src

Constructors are functions that instantiate values. The =Type= next to them is what you have to pass into the function

What's happening under the hood, is that we get a function
#+begin_src haskell
constructor1 :: Type1 -> sumTypeName
#+end_src

Sum types say that the data type can be instantiated by any of the listed constructors.

=deriving(Show, Eq)=: these are properties we give our defined type
- =Show= allows us to print it to the terminal
- =Eq= allows us to use ==== on it


*** Product Types

#+begin_src haskell
data prodTypeName = prodTypeName
  { regionName        :: Text
  , regulatoryBody    :: Maybe Text
  , sovereignRiskTier :: Int
  } deriving (Show, Eq)
#+end_src

This says that the data constructor is also =prodTypeName=
- this tells us there's only one valid way to construct the data form

The info inside of the curly brackets are *records*: they tell us what information our data type must contain (it has to contain /all of them/)

=field :: Type= means that the field has the type =Type=

=Maybe= is a nice way of preventing null-pointer errors. =Maybe Type= means that either the field can be type =Type= or type =Nothing=


** Synonyms

#+begin_src haskell
type aliasName = Text
#+end_src

This creates an alias for the type =Text=
- it's basically just used to help make your code more readable

** newtype

=newtype= doesn't have any runtime cost, unlike =data=


#+begin_src haskell
newtype SemanticID = SemanticID Word64
#+end_src

In this snippet, two things are happening:
1. We're defining a new type called =SemanticID=
2. We're also defining a data constructor named =SemanticID=

The point is that now that SemanticID is /created from/ a 64-bit integer, but it isn't itself considered a 64-bit integer by the program
- this is a form of *type safety*
- it says that we can't just pass any random 64-bit integer into a function expecting a SemanticID; we have to explicitly say that our integer is of type =SemanticID=
- very cool!
   

** Characters

All characters are *boxed*
- they're their own independent objects living in some random place on the heap

They're made up of
- header (8 bytes)
- unicode point data (4 bytes (32-bit unicode), padded to 8)

** Lists

Lists are denoted with square brackets, like =[1,2,3]=, but their actual structure under-the-hood is *nested constructors*:

#+begin_src haskell
1 : (2 : (3 : []))
#+end_src

The colon =:= is called a *node* or a *cons operator*. It's actually a function with shape
#+begin_src haskell
(:) :: a -> [a] -> [a]
#+end_src
It takes an element of type =a= and a list of type =[a]= and returns a list of type =[a]=
=::= defines a type

A node contains two pointers:
1. to the associated character
2. to the next node (or to =[ ]=)


#+begin_src haskell
myList = 1 : 2 : 3 : []

-- is the same as
1 : (2 : (3 : []))
-- because : is defined to work from right to left


(:) :: a -> [a] -> [a]
#+end_src

*** Disadvantages

Lists are stored [[id:a078425d-e64f-4755-ae88-6470c5d6f0c8][non-contiguously]]
- so you constantly get cache misses

Because lists are generated lazily, if you need to go through an entire list, it's inefficient

A single character usually takes 1-2 bytes in another language. In a haskell list, on average, a character takes *up to 24 bytes*
because it's really made up of
- a node
- two pointers
- a boxed character header

*** Advantages

Lists are generated lazily
- so you can actually manipulate lists that are *larger than your RAM*
- you just create the list as you go
- and as you finish a step and move on to the next one, the GC reclaims the node

You can prepend data in O(1)
- you just point into the beginning of your list

** Strings

In basic haskell, =String= is an alias for a list of characters:
#+begin_src haskell
type String = [Char]
#+end_src

Consequently, it's a long chain of nodes:
#+begin_src haskell
h : e : l : l : o : []
#+end_src

Since each character is blocked, they're all scattered around the heap, which makes them slow to read

*** Concatenation

=<>= is actually the operator for the *semigroup* typeclass

* Modules

#+begin_src haskell
module Name where

import Namespace1 (Type1)
import Namespace2 (Type2)
#+end_src

=module...where= says that anything within the file belongs to the module Name.

=import Namespace (Type)= grabs certain types from external libraries

** Data.Bits

Gives you highly optimized bit-fiddling operations that compile down to assembly instructions, like =popcnt= and =pxor=

** Data.Text

Treats strings as contiguous byte arrays encoded in UTF-16
- stores the length of the string and the current offset

Because it's contiguous, you don't need pointers, since you know that the next character is just in the next part of the cache line
- characters take up *2 bytes*

*** splitOn

Text \to Text \to [Text]

Scans the text block for every occurance of a fixed string and breaks it into a list at those points.
- instead of creating a list made up of the strings of text you get, it just creates a list of pointers to the memory address and offset of each of the chunks in the list

*** strip

Text \to Text

Trims all leading and trailing whitespace
- just changes the length and offset to start after the whitespace and end right before

*** null

Text \to Bool

Checks if your text is empty
- O(1) by just checking if length = 0

*** toLower

Text \to Text

Makes all of the letters lowercase
- creates a new array on the heap and writes the lowercase version of the text

*** words

Text \to [Text]

Splits text into a list of words
- stores the pointers and lengths

It's actually smarter than =splitOn=, which  doesn't know how to handle double-spaces or other kinds of white spaces, like tabs, newlines, and carriage returns.

*** filter


(Char \to Bool) \to Text \to Text

Retains only the characters that match a given filter

Note that unlike =words=, this returns plain text, *not a list*.
- so it can't just handle things using pointers
- it rewrites the filtered text as a new array

*** length

Returns the total number of characters
- O(N) (surprising!). It's because UTF-16 is variable-width, so some characters take up more or fewer bytes than others

*** intercalate

Takes in a seperator list and a list of lists
- sticks the seperator list between every element in the list of lists and flattens the result

#+begin_src haskell
intercalate :: [a] -> [[a]] -> [a]
#+end_src

** qualified

#+begin_src haskell
import qualified Data.Text as T
#+end_src

=qualified ... as= says that every function imported from =Data.Text= will be prefixed by "T."
- this helps avoid namespace collisions

* Functions

#+begin_src haskell
computeSimHash :: [Text] -> SemanticID
computeSimHash tokens = SemanticID $ foldr buildBits 0 (zip [0..63] vectorSums)
  where
    tokenHashes = map hash64 tokens
    vectorSums  = foldr accumulate (replicate 64 0) tokenHashes
#+end_src

=foldr= takes a higher order function, an initial accumulator state, and a list, and collapses the list down to a single value from /right to left/

=where= gives the variables *local scope*
=let ... in= also gives local scope


=zip [0..63]=

=zipWith= takes a function that accepts 2 arguments, and zips two lists together by applying the function to their elements.

=\= is the syntax for an anonymous (lambda) function

=.= is the function composition operator (it goes from right to left, so it behaves like g \circ f)

=$= applies a function to a value to produce a value
- it's basically element application
  =f $ x= behaves like f(x)
- without it, lines parse from left to right
- using the dollar sign basically just lets us avoid a bunch of parentheses

=<$>= takes a function and reaches inside of a container to apply the function inside the container  

#+begin_src haskell
tokenHashes :: [Word64]
tokenHashes = map hash64 tokens

-- it's the same as
-- const tokenHashes = map(hash64, tokens);
#+end_src

This snippet defines =tokenHashes= as a list (square brackets) of integers
- the syntax =:: Type= can be thought of like a map from the terminal object into =Type=

The next line then describes how we get this list of integers  
- =map= is a function that takes two arguments
- it uses *currying*, so really what ends up happening is you first get a function =(map hash64)= which takes an argument =tokens=

  

* Case

#+begin_src haskell
case sentences of
    []         -> ""
    [single]   -> single
    (first:xs) -> first <> " . " <> last xs
#+end_src

=<>= monoidal concatenation

* Pointfree Style


#+begin_src haskell
-- Pointful (Explicit values/elements)
process txt = show $ hash64 $ txt

-- Pointfree (Pure Category-theoretic Arrow Composition)
process = show . hash64
#+end_src

* Fat Arrow

==>= denotes a *type-class constraint*
- it says /you can only execute the following if these constraints are satisfied/

* Monads

Ordinarily, the compiler is able to execute things in whatever order will be most optimal
- there's no native concept of time or sequence in Haskell

Monads *force things to evaluate in sequence*

** When would you use this?

When interacting with hardware states
- you can't read a memory address before you allocate it

** Monad Types

*** PrimMonad

Can execute raw, low-level things

**** IO Monad

Can mutate memory, talk to the disk, print to the screen, write to a file

**** ST Monad

Memory *sandbox* that allows mutation, but can't interact with the outside world

Designed for single-thread deterministic execution
- you can't pass an ST vector between concurrent threads, because it's stuck in the sandbox
- you can't write to logs or do any nice debugging

*** PrimState

**** RealWorld

The IO monad has this state

**** s (sandbox)

The ST monad has this state

* Optimizing

** Streaming-Mutation

When you mutate a string, you never want to store the whole string and then mutate it, because you'll get a string scattered throughout the heap

Instead, you modify in place, one letter at a time
- you keep your string in the L1/L2 cache

* Scoping

** let ... in

=let= can be used anywhere in your code that a value is expected
- it defines local variables

=in= defines the expression where the local variables are valid

#+begin_src haskell
calculateArea :: Double -> Double
calculateArea radius = 
    let piVal = 3.14159
        r2    = radius * radius
    in piVal * r2
#+end_src

=let ... in= is used typically inside of lambda functions or if-thens, where =where= can't be used

** where

It's very similar to =let=, but you have to *use it inside of a function*
- the nice thing is that =where= automatically knows about every argument in the function it's attached to
  
#+begin_src haskell
calculateArea :: Double -> Double
calculateArea radius = piVal * r2
  where piVal = 3.14159
        r2    = radius * radius
#+end_src

It can also work across sum-types:

#+begin_src haskell
describeNumber :: Int -> String
describeNumber n
    | n > 0     = "Positive: " ++ show n
    | n < 0     = "Negative: " ++ show n
    | otherwise = "Zero"
    where nSquared = n * n -- This nSquared is available to ALL guards (|)
#+end_src

* Pattern Matching

** case ... of

=case= takes a value and compares it against a series of patterns, to decide what to return

#+begin_src haskell
case expression of
    pattern1 -> result1
    pattern2 -> result2
    _        -> defaultResult
#+end_src

functions in haskell are computed using =case...of=, under the hood

#+begin_src haskell
factorial :: Int -> Int
factorial x = case x of
    0 -> 1
    n -> n * factorial (n - 1)
#+end_src

=case ... of= and =if ... then= are computed in the exact same way
- so they're equally performant
but =case= is often clearer, and allows you to handle more cases, without having to nest a bunch of if statements.
