:PROPERTIES:
:ID:       8af04d1b-72d0-410b-8ac4-91b490c5b8ec
:END:
#+title: korean film
#+filetags: :film:art:

* References



* Summary

Korean film feels *fractured* to me.
        * Japanese occupation (1910-1945)
        * Korean war (1950-1953)
        * Dictatorship (1960-1980)
        * IMF crisis (1997)


* Kino-drama (1919)

Actors performed live on stage, with  a projector providing a moving backgroun

** The Righteous Revenge

* Silent film

=Benshi:= Theatres playing silent films would have a live narrator, called a Benshi, standing next to the screen. People working as Benshi ended up becoming quite famous

=Ad-libs:= Benshi would add in anti-colonial rhetoric and political commentary

** Plighted Love Under the Moon (1923)

The first silent Korean film

* Japanese Occupation

** Arirang (1926)

It's about a mentally unstable Korean man who kills a Japanese police informant. 

* Post Occupation

** Viva Freedom! (1946)

* Korean War (1950)

The war destroyed the cinema architecture on Korea: theatres were burned, equipment was stolen and destroyed, and filmmakers were killed or kidnapped

* Post Korean War (1953)

After the war, South Korea was *one of the poorest nations on earth*. The South Korean President Syngman Rhee tried to rebuild the national spirit through film: all of cinema was *exempt from taxes* 

South Korea after the war had *huge income inequality*, which influences Korean media's focus on the rich and poor in things like /Snowpiercer, Squid Game, Mickey 17/ 

** Madame Freedom (1956)

** The Housemaid (1960)

* [[id:9e2eb54f-e86d-4bdb-8577-f63a91074ab6][asian financial crisis]] (1997)

During the crisis, the South Korean economy collapsed; once again, South Korea was dirt-poor. This time, in trying to rebuild the nation, the government focused on *exporting culture* 
        * this is where the kpop and kcomms industries were born

=Cultural technology:= The focus on highly efficient delivery of culture created the modern exploitative kpop industry. 

=Critique commodity:= The exploitative media and corporate institutions led to Korean cinema becoming hyper critical of capitalism. Realizing this was profitable, those same media companies then started funding these film projects.

* Hell Joseon

* Minjung (1980s)

=No big funding:= The Minjung film movement believed that accepting funding from huge corporations tainted the film. Similarly with corporate distribution or state approval

** Oh! Dream Land (1989)

Critiqued US imperialism and military brutality

* 


* Han (collective unresolved grief)

This unresolved trauma stems from foreign occupation, dictators,



* Authority

Authority figures are viewed as corrupt

* Fracture

** Tonal whiplash

laughing through the pain

There is no stable mood; it reflects the instability that Koreans feel around their society; 

** Genre mixing
