:PROPERTIES:
:ID:       b80bebf5-3a44-4ade-a05e-64b330392656
:END:
#+title: abstract expressionism
#+filetags: :cia:cold_war:

* References



* Summary

* Cold war

** CIA

The CIA actually used the *Congress for Cultural Freedom* to fund abstract expressionism as a /soft power tool against the Soviets/

They didn't care at all about the artistic merits of the movement. When AE was taking off, they decided that it would be the perfect antagonist to *Socialist Realism* --- instead of an art movement that was prescribed by the state, they wanted to show off the US as a beacon of free expression.

** MoMA

The Museum of Modern Art was actually funded by the CIA

The CIA funded shell foundations, wealthy patrons, and museums to buy and show abstract art both in American and abroad

** The art world

At the time, the art world didn't care about the US; it was seen as a *backwater* 

The Soviets actually used this as part of their propaganda: they pushed the narrative of the US as an *uncultured, captialist* society, more interested in Coca-Cola and gadgets

** Socialist Realism 

Socialist Realism was a state-mandated art style overseen by Stalin. You weren't allowed to paint whatever you wanted; it had to be this particular style, with particular subject matter, etc.
        - realistic
        - literal
        - glorify communist workers, factories, and/or leaders
