:PROPERTIES:
:ID:       7e9ed150-1fdf-46e2-8458-f424356ae2c7
:END:
#+title: criticism
#+filetags: :literature:

* References



* Summary


* Virginia Woolf

Jacob's Room (1922) was consider too difficult and stuck up
Three Guineas (1938) was considered too preachy

* John Keats

Endymion (one of my favourite poems of all time) was lambasted by everyone, including Keats himself. He was considered part of the /cockney school of poetry/, which was looked down upon by the upper-class poets of the time.

        "The phrenzy of the /Poems/ was bad enough in its way; but it did not alarm us half so seriously as the calm, settled, imperturbable drivelling idiocy of /Endymion/."

        --- Lockhart in Blackwood's magazine

* William Shakespeare

Dryden viewed Shakespeare as a diamond in the rough. He was seen as someone with *no artistic refinement* 
        - he hated that Shakespeare tried to mix tragedy and comedy, saying that the two forms would "cancel and destroy each other"
        - the language was too bloated and not as nice as that of Dryden's time

Dryden straight-up *rewrote the plays* to make them better. His /All for Love/ is his rewrite of /Antony and Cleopatra/. 

Samuel Johnson hated that Shakespeare had no clear moral lesson in his work. He also /despised/ puns and felt like Shakespeare stuck them into too many dramatic scenes. He also felt like Shakespeare just gave up by the end of each of his plays --- the endings were all sloppy and rushed
