:PROPERTIES:
:ID:       1c00eb55-101f-4f11-b54d-10e27da4a9f2
:END:
#+title: operators
#+filetags: :math:func_anlysis:

* References

* Summary


* Definitions

** Types of Operators

*** Self-Adjoint

*** Symmetric

\[
\langle Ax \mid y \rangle= \langle x \mid Ay \rangle
\]

*** Closed

*** Continuous

*** Bounded

A linear operator $A: X \rightarrow Y$ is called /bounded/ if it maps bounded subsets to bounded subsets.

* Theorems

** Spectral Theorem

*** Projection valued measures

** Closed Graph Theorem

A linear map between Banach spaces is continuous if and only if its graph is closed.

*** Purpose

Makes proving continuity easier; you never have to show convergence, you just need to prove you converge to the correct thing.

** Uniform Boundedness Principle



*** Purpose

** The Opening Mapping Theorem



*** Purpose

** Bounded Inverse Theorem

*** Purpose



** Hellinger-Toeplitz

Let $A$ be a symmetric operator defined everywhere on a Hilbert space. Then $A$ is bounded.

** Continuous = Continuous at a Point

** Continuous \subset Bounded



*** Bounded = Continuous

Let $A$ be a linear operator from a bornological space to a locally convex space. Then $A$ is bounded if and only if it's continuous.

**** Counter-example: Weak Topology

** GNS Theorem

 Every commutative unital \(C^{*}\)-algebra A is isometrically *-isomorphic to C(K), the space of continuous complex-valued functions on a compact Hausdorff space K

Every arbitrary \(C^{*}\)-algebra A admits a faithful, isometric *-representation as a closed subalgebra of B(H), the algebra of bounded operators on some Hilbert space H.

** Double Commutant Theorem

** Kaaplansky Density Theorem

** Tomita-Takesaki Theorem

For any von Neumann algebra in standard form with a cyclic and separating vector, there exists a canonical one-parameter quantum evolution group (modular automorphism group).

** Wintner-Wielandt Theorem

** Stone-von Neumann Theorem

** Mackey-Arens Theorem

** Baire's Category Theorem

** Banach-Alaoglu Theorem

** Krein-Milman Theorem

** Bochner-Minlos Theorem

** Minlos-Sazanov Theorem

** Hahn-Banach Theorem

Let $p: V \rightarrow \mathbb{R}$ be a seminorm on a real or complex vector space. Given any linear functional $\phi: U \rightarrow k$ on a subspace $U \subseteq V$ such that $|\phi| \leq p$ on $U$, there exists a linear functional $\Phi: V \rightarrow k$ such that
$\Phi = \phi$ on $U$ and $|\Phi| \leq p$ on $V$.

*** Intuition

It's actually quite easy to find bounded linear functionals: you just need to ch
Bounding a linear functional on a subspace is enough to be sure that it can be 

*** Purpose

It assures you that there are enough continuous linear functionals, but that's sort of an abstract reason.

Concretely there are 3 use cases:

**** Separation of Points

If you have two disjoint convex sets, you can find a closed hyperplane that separates them


**** Existence Proofs

Consider a problem like finding the shortest distance from a point x to a closed subspace C.

You can find a linear functional such that
$\phi(c) = 0$ for all $c \in C$
$\phi(x) = 1$
$||\phi|| = 1/d$

**** Embeddings

Given any Banach space $X$ and $x \ne 0$ we can find some functional with
$||\phi|| = 1$ and $\phi(x) = ||x||$

From here, we can embed $X$ into $X^{}''$ (the double continuous dual)
$\phi: X \rightarrow X''^{}$ with $\phi_{x}(f) = f(x)$

We need to show that $||\phi_x|| = ||x||$
Now $||\phi_{x}|| = \sup_{{||f|| \leq 1}} |f(x)|$

$||f(x)|| \leq ||f|| ||x|| \leq ||x||$ for $||f|| \leq 1$
And so $||\phi_{x}|| \leq ||x||$.
For the other direction, we use the HB theorem:

We look at the subspace generated by $x$ and let $\psi(\lambda x) = \lambda ||x||$
Its norm is 1
Use HB to extend this to the full space $X$, and we get a linear functional $||\Psi|| \leq 1$ with $\Psi(x) = ||x||$
So $||\phi_{x}|| = \sup_{{||f|| \leq 1}} |f(x)| \geq \Psi(x) = ||x||$

**** Generalized Limits

You can define limit functionals on all convergent sequences, and extend that to all bounded sequences.

** Spectral Radius

** Riesz-Schauder Theory
