:PROPERTIES:
:ID:       d9266e59-b649-4c42-895f-e664d85d21ea
:END:
#+title: conference notes
#+filetags: :math:conferences:presentations:

* References
 European and Pacific Theoretical Physics

Ottawa-Carleton Number Theory Group

Math Picture Language seminar 

European Non-Associative Algebra Seminar

NCTS International Geometric Measure Theory Seminar

Virtual seminar on geometry with symmetries

CT2026

* Chelsea Walton



quantum yang baxter
quantum reflection equation
R_1_2 K_1 R_2_1 K_2 = K_2 R_1_2 K_1 R_2_1

K_i is a reflection of particle i against the boundary

brochier (2013) - braided c-module category
(actegory)

the braiding of the action is the reflection
$\sigma : X \cdot M \rightarrow X\cdot M$

coxeter groups have graphs associated to them

type A gives you yang-baxter
and so correspond to braided monoidal categories

type B has a single reflection and corresponds to these braided c-module categories



quasitriangular hopf algebras
its modules become braided monoidal categories

braided morita equivalence
between quasitri hopf algebras
the equivalent is if their (H,R)-mod categories are equivalent

thm shimizu 2010
braid group represents gives braided morita invar

if braided morita equivalent then represents of braid groups are isomorphism

other side

quasitri h-comodule  algebra

the category of mods is a c-mod category
to make it braided, you need a K-matrix (like the R-matrix)

you get a braided morita equivalence

fd quasitri coideal subalgs that are braided morita equivalent gives equivalent of represents
** Categorical Centers

for yang baxter
take a monoidal category, you get a braided monoidal category 
- take the drinfled center
- the drinfled center is braided morita equivalent to the drifeld double modules category (in the fd case)

for the reflection pic
laugwitz-walton-yakimov (2025)
- reflective center
- the reflective algebra is the thing corresponding to the drinfeld double

throw in ribbons and you get modular structures
** non degeneracy

given a finite tensor braided monoidal category

non deg means that the drinfeld center factorizes
- ex factorizable hopf algebras

equivalent to a center coend being an actual hopf algebra with a non-degen laplace pairing

[shimizu 2019]

the reflective case
- the end has a certain non-degen pairing
- equivalent to being factorizable

future work: quantum group versions of these reflective things
** Speculations

look at all the coxeter types
- can you always represent these with string models?

- what's the categorical version?

- is there a physics version of each of these?

- is there a single equation that specializes to yang baxter and the reflection
* Augustina Czenky 

Tensor categories are the pre-categories of modular tensor categories

You want both an abelian and a monoidal structure

Homs are finite-dimensional  vector spaces.

You want to be rigid: Duals exist

And you need the endomorph of the unit are the base field (aka the unit is simple)

For a mondular category you need
- a braiding

fusion categories are tensor categories with
- the category is semisimple
- the category has fin many simples
- the rank is defined to be the number of simple objects

A pre-modular category is a ribbon braided fusion category
- the ribbon is a certain collection of endomorphisms $\theta_{X}: X \rightarrow X$ for all X
- you can define an *S-matrix*
- S = Tr(\sigma_X_Y \sigma_Y_X) with X,Y simple

If the S-matrix is invertible, you get a *modular cat* 
** Example

Tambara-Yamagami

You start with a finite abelian group and take a symmetric bicharacter
- this should be a laplace pairing on kG

The simple objects are the elements of G along with one additional object

Fusion rules
$a \otimes b = ab$
a \otimes x =x \otimes a = x
x \otimes x = \oplus_a_\in_A a

If the order of the group is odd and the bicharacter is non-degen you get a unique modular structure
* Problems

Classification: organizing what we know
- rank finiteness conjecture (2013)
- only finitely many modular categories of a fixed rank

Construction: new from old

Frobenius-Peron dim
- if 1 you're called pointed
- if Z you're equivalent to representations of a quasi-hopf alg

For fusion categories, classification by rank is very hard
- only done up to rank 2

For modular categories 
- if fp dim is odd then we know the case of rank \leq 11
       - you're pointed (classified by group data)
- in general we have classification up to rank 12


Question: Can you find odd FP-dim MTC which is perfect (only invertible object is the unit)?
- this is very difficult, but people think the answer is no

perfect: evaluation and coevalution are isos

** Future directions

non-algebraically closed field
char p
non-semisimple case

* Marino Gran

Hopf formulae for cocommutative Hopf algebras

Semiabelian categories
- non-abelian homological algebra.

Def: finitely complete category with
- 0 object
- binary coprods
- Barr-exact (factor as regular epi followed by mono)
       - regular epis are pullback stable
- bourn-protomodular

The canonical morph from coproduct to prod is not an isomorphism

** Hopf Algebras

Take cocommutative hopf algebras. 
- ex group algebra
- symmetric algebra
- tensor algebra

The category of cocommutative Hopf algebras is semi-abelian 
- it's also strongly protomodular

The category of commutative and cocommutative Hopf algebras is abelian


In groups, free resolutions' second homology has a hopf-formula

** Galois Theory

You want to view a Hopf algebra as a quotient of some projective resolution and then take the universal central extension

You get a galois groupoid

** Yang Baxter

A skew brace gives you bijective solutions to YB

* James Hefford

Compact Closure formalizes dual objects
- something like traced

Being partially traced is something like nuclear and trace ideals

These are useful for conformal field theories
- then you want to look at extended versions of these field theories.
- james is just looking at extending to the bicategory case

Looking at maps into hilbert spaces from conformal bordism category

Compact closure allows you to define a trace 
- so I'm thinking it's something like a Type 1 von Neumann algebra.
- finite-dimensional Hilbert space
- and d-dim bordisms for any fixed d



** Partial Compact Closure

- All Hilbert spaces.
       - The Hilbert-Schmidt maps have transposes
       - the identity maps are usually not hilbert schmidt
       - but these maps are actually closed under composition with /any/ map (so it's an ideal)


Nuclear ideals
- assume you have a tensor-star category.
- the idea is to get something that ends up being all the trace-class maps
- hilbert schmidt form a nuclear ideal
- bordism-conf with objects disjoint unions of circles and morphs conformal cobordisms
       - except this has no identity maps!
       - If we add in the diffeomorphisms, we fix it, and then the conformal cobordisms form a nuclear ideal


the conformal cobordisms are basically the trace class maps

You can define a trace ideal
- this is really the trace class maps

*** Nuclear Implies Trace

If C has a nuclear ideal it also has a trace ideal

** Field Theories

CFT is a symmetric monoidal functor
[Segal]
Z: Bord^conf \rightarrow Hilb
where each Z(A) is trace class for all A and tr Z(A) = Z(tr A)

but really since Bord isn't a category we really want a /nuclear functor/ to make it more rigorous

** Extended to 2

To get the extended version of the conformal field theory you need to define a 2-trace ideal
- and you end up using things like biprofunctors, pseudocoends


* Aaron Fairbanks
Comonads as Spaces


Comonads on Set give you a generalization of topological spaces
- the adjunction between Sh(X) and Set is comonadic
- you can recover the topological space X from the comonad

You can look at comonads on any category but we'll just stick with Set

** Subbasis

P: B \rightarrow Set
B is the poset of subasic opens
P is the forgetful functor sending you to a set of points

*** Density Comonad

The left kan ext of P along itself

It's also given by the adj Psh(B) and Set

It's also the free comonadic functor extending P

*** Density Comonads = Topological Spaces

*** Toposes with enough points = Pullback-preserving comonads on Set

They're also called ionads [Richard Garner]

Ionads generalize both top spaces and categories

Categories are the *polynomial comonads* on Set

$x^{3} + x = x(x^{2} + 1)$

corresponds to the category with two objects and two morphisms between them

*** Take density comonad where the subbasis is all sets with surjections

This gives you a one-point space

** Basis

When is a subbasis a basis?
A functor is dense if the codomain embed in presheaves

$(-)^{F}: $ is fully faithful

A subbasis is a basis if and only if the inclusion into Sh(X) is dense actually!

So a basis is 

S^<P> \rightarrow Psh(B) is an embedding, where the domain is coalgebras

[my building's fire alarm went off and I missed the end of the talk :I]

