:PROPERTIES:
:ID:       2d82b7e0-703b-4e07-9630-ab21e88e7304
:END:
#+title: topological quantum field theories
#+filetags: :math:tqft:physics:

* References

* Summary

Topological quantum field theory is normally some topological variation on a [[id:beb0fb6e-9b8a-4f4f-8264-8e4c56a3b9c1][yang-mills field theory]]. We either remove the metric (Chern-Simons) or we start with the metric and pass into a subspace that doesn't use the metric (Witten)

* Definitions

** Wilson loops

Given a [[id:beb0fb6e-9b8a-4f4f-8264-8e4c56a3b9c1][yang-mills field theory]] with connection \(A\) on a spacetime manifold, the Wilson loop operator is
\[
W(\gamma) = Tr( \mathcal{P} e ^{i \int_{\gamma} A_{\mu} dx^{\mu}})
\]
for any closed loop \(\gamma\), where \(\mathcal{P}\) is the /path-ordering operator/ 

*** Parallel transport

We are parallel transporting the /wavefunction/ 

*** Physics Intuition

These arose in studying quantum chromodynamics

A Wilson loop  (in spacetime) is what you get when you track the phase shift of a particle moving in a closed loop in spacetime.

=Confinement:= They were first invented as a way of explaining why quarks are never found in isolation

=Experiment:= We imagine a quark-antiquark pair blinking into existence at a positive separation, and trace their paths in spacetime, and then they blink out of existence. If you just have the quarks behaving independently, you get two separate curves. It turns out that the thing you get *is not gauge invariant.* But you can make it gauge invariant if you connect these two curves into a loop --- in order to do so, you need to say that when the particles pop into/out of existence, they have something *linking them together* 

=Expectation value:= If you compute the expectation value of a Wilson loop, the integral you take basically fills in the loop, so you get a world sheet. It turns out
\[
\langle W_{C} \rangle \sim e^{-V(R) T}, \; T \rightarrow \infty
\]
where \(R\) is the separation between the particles

In EM your potential dies off as \(1/R\), but it turns out for QCD that the potential increases as \(R\). This is why quarks are *confined* 

=TQFT:= However, if you calculate Wilson loops in a \((2+1)\)-dimensional TQFT, the \(R\) and \(T\) dependence disappears; quarks (or their tqft equivalents) don't have confinement; the only thing that matters is how the worldlines are *braided*. The particles in the TQFT are *anyons* 

The expectation value of the Wilson loops in this case is the *Jones polynomial* 

** Wilson junction

This is the baryonic version of the Wilson loop

The structure you get looks like an \(M_{3}\) lattice



* Examples

** Witten's TQFT

=Starting place:= Take an \(\mathcal{N} = 2\) supersymmetric Yang-Mills theory in 4D. 

** \(BF\) Theory

If we try to do [[id:beb0fb6e-9b8a-4f4f-8264-8e4c56a3b9c1][Yang-Mills theory]] in the case that we don't have a metric, we immediately run into a problem: we can't define a Hodge star operator, and thus we have no obvious way of defining an action for our theory.

To fix this, we assume that there's some other independent field, given by an \((n-k)\)-form \(B\), so your action is 
\[
\int Tr(B \wedge F)
\]


** Chern-Simons Theory

In Yang-Mills, you start with a closed orientable (pseudo)Riemannian manifold with a principal \(G\) bundle and connection \(A.\) The metric allows you to define a Hodge star operator, which then gives you the ability to form an integral
\[
\int_{M} Tr(F \wedge \star F)
\]
which is the *Yang-Mills action*, where \(F = dA + A \wedge A\) is the curvature.

If we don't have a metric, we can't get a Hodge star operator, so we need something else to integrate. 

=3D:= In the case that your manifold \(M\) is *three-dimensional*, the obvious thing to do is to try to take \(\int Tr(A \wedge F)\). 

It turns out, this doesn't work --- it *isn't gauge-invariant*. If we take a gauge transformation \(A \rightarrow g^{-1} A g + g^{-1} d g\) (note that this transformation shows up because of the fact that we use the *covariant derivative* \(A + d\))



=Solution:= The actual Chern-Simons functional comes from mathematics: in four dimensions the *second Chern class* has the form
\[
Tr(F \wedge F)
\].
You then try to work backwards; since your manifold is only three dimensional, you try to write \(Tr(F \wedge F)\) as an exterior derivative of a three-form.

\(A \wedge A\) is a *self-interaction* 


*** Intro

This is the canonical example of a topological quantum field theory from a mathematical physics perspective.

It's based on Yang-Mills theory.

In Yang-Mills theory, we start with a smooth orientable, compact manifold $M$ without boundary and a metric $g$, which we use to construct the *Hodge star operator* $\star$. 

=Conditions:= Compactness allows us to easily integrate over everything. The metric and orientability give us the Hodge star operator. The orientability is also necessary to define a global integral. And the lack of boundary makes it so that we don't have to keep track of boundary conditions

=Action:= The action takes the form

$S_{\text{Yang-Mills}} = \dfrac{1}{2g^{2}} \int_{M} Tr(F \wedge \star F)$

where $F$ is the curvature 2-form $F = dA + A \wedge A$. In local coordinates this is
$F_{\mu\nu} = \partial_{\mu} A_{\nu} - \partial_{\nu} A_{\mu} + [A_{\mu}, A_{\nu}]$

=Removing the metric:= What if we don't have a metric? For Chern-Simons theory, we take a smooth, compact, oriented *3-manifold* $M$ without boundary, equipped with a principal $G$-bundle $P$, for a compact Lie group $G$.

We then take a *connection 1-form* $A \in \Omega^{1}(M, \mathfrak{g})$. The Chern-Simons action is then

$S_{\text{Chern-Simons}} = \dfrac{k}{4 \pi } \int_{M} Tr(A \wedge dA + \dfrac{2}{3} A \wedge A \wedge A)$

=Note:= $A$ is a *Lie-algebra-valued* differential form, not a scalar valued one. This is why we don't have $A \wedge A = 0$.

=Lie-algebra forms:= These have the general shape $A = \sum_{i} A_{i} dx^{i}$, where $A_{i} \in \mathfrak{g}$ are matrices.

**** Example

If $A = A_{1} dx^{1} + A_{2} dx^{2}$, then $A \wedge A = A_1 A_2 dx^{1} \wedge dx^{2} + A_{1} A_{2} dx^{2} \wedge dx^{1} + 0 + 0 = [A_{1} , A_{2}] dx^{1} \wedge dx^{2}$

**** Applying the Trace

$Tr(A \wedge B) = (-1)^{\abs{A} \abs{B}} Tr(B \wedge A)$.

In particular $Tr(A^{\wedge 4}) = (-1)^{1 \times 3} Tr(A^{\wedge 4})$, and so it must be zero.

**** Hodge Star

In 4D, the Hodge star is an idempotent endomorphism on 2-forms, so we can decompose any 2-form as

$F = F^{+} + F^{-}$, where $F^{\pm} = \dfrac{1}{2}(F \pm \star F)$ are (anti)symmetric

=Note:= $F^{+} \wedge F^{-} = 0$. Thus we can write

\begin{equation*}
Tr(F \wedge F) = Tr(F^{+ \wedge 2}) + Tr(F^{- \wedge 2}).
\end{equation*}

** Exact Case

In the case that $M$ is itself a boundary of a 4-manifold $X$, we would have

\begin{align*}
d  Tr(A \wedge dA + \dfrac{2}{3} A \wedge A \wedge A) &= Tr(d (A \wedge dA) + \dfrac{2}{3} d(A \wedge A \wedge A)) \\
&= Tr(dA \wedge dA - A \wedge d^{2} A + \dfrac{2}{3} (dA \wedge A \wedge A - A \wedge dA \wedge A + A \wedge A \wedge dA)) \\
&= Tr(dA \wedge dA + 2 dA \wedge A \wedge A)
\end{align*}

We also have

\begin{align*}
Tr(F \wedge F) &= Tr((dA + A \wedge A) \wedge (dA + A \wedge A) ) \\
&= Tr(dA \wedge dA + dA \wedge A \wedge A + A \wedge A \wedge dA + A \wedge A \wedge A \wedge A)
\end{align*}

$Tr(A^{\wedge  4}) = 0$. So we have

$Tr(F \wedge F) = d Tr(A \wedge dA + \dfrac{2}{3} A \wedge A \wedge A)$

This means that $Tr(F \wedge F)$ is *exact*, so integrating over it is equivalent to integrating over the boundary:

$\int_X Tr(F \wedge F) = \int_{\partial X = M} Tr(A \wedge dA + \dfrac{2}{3} A \wedge A \wedge A)$,

recovering the Chern-Simons action in the case that $F = \star F$ (the field is *self-dual*)
- these self-dual fields are called *instantons*

Now let's write $F = F^{+} + F^{-}$. 

And so $\star F = F^{+} - F^{-}$. We get

$S_{\text{Yang-Mills}}(F) \sim \int Tr(F \wedge \star F) = \int Tr(F^{+ \wedge 2}) - \int Tr(F^{- \wedge 2})$

$S_{\text{Yang-Mills}} (F) = S_{\text{Chern-Simons}}(F^{+}) - S_{\text{Yang-Mills}}(F^{-})$

=Hyperplane:= The Chern-Simons part of the theory corresponds to a particular hyperplane

** Fractional Quantum Hall Effect

** 3D Quantum Gravity

* Flat Connections

* Floer Homology

* Functorial Field Theories

** Topological quantum field theory 

We take closed, oriented 2-manifolds, and assign them finite-dimensional Hilbert spaces, called the *spaces of conformal blocks* 

Then the 3-manifolds (the cobordisms) give us a few things:
- when we have the shape $\partial_{i} M = \emptyset$, $\partial_{f} M = \Sigma$, then our field theory is assigning a state vector of Hilbert space on $\Sigma$.
- when $\partial_{i} M = \emptyset$, $\partial_{f} M = \emptyset$, we get a map $\mathbb{C} \rightarrow \mathbb{C}$, which just picks out a single complex number. The is the *partition function* or *topological invariant* of the theory.

=How this works in physics:= If we take an integral over a manifold with boundary, we need to keep track of the boundary conditions
\[
\Phi(\varphi) = \int_{\phi|_{\partial M} = \varphi} D\phi e^{-S[\phi]} .
\]
For every boundary condition \(\varphi\), we get a different result on our integral. The functional \(\Phi\) is an element of a vector space, which turns out to be a Hilbert space.

=Question:= Why do we have more than one element in our Hilbert space? What are all these different functionals that we get? 

=Answer:= The integral I wrote above is integrating over the manifold \(M\). This manifold is the *cobordism.* We get a different functional for every possible cobordism that maps \(\emptyset \rightarrow \partial M\). So really, what we should write is that we have a fixed boundary \(\Sigma  \), and the Hilbert space assigned to \(\Sigma \) is made up of functionals like 
\[
\Phi_{M}(\varphi) = \int_{\phi|_{\Sigma } = \varphi} D\phi e^{-S[\phi]} ,
\]
where \( \partial M = \Sigma .\)

We can also use other functionals, like correlation functions, I assume.

=Note:= This relies on there being topologically distinct cobordisms that have the same boundary. This is very much a thing. As a basic example, take any two closed manifolds; they both have empty boundaries. As a more complicated example, take some manifold with whatever boundary and then *add a handle to it.* That's a great trick.

=Duals:= You interpret cobordisms \(\emptyset \rightarrow \Sigma \) and \(\Sigma \rightarrow \emptyset\) as duals (one is a bra, the other a ket). Then the expectation value is a map \(\emptyset \rightarrow \emptyset.\) This corresponds to a path integral over the whole closed manifold

=Surgery:= This allows you to compute the actual path integrals over the closed manifold by doing surgery and keeping track of the boundaries with Hilbert spaces. That's a pretty neat trick.

=Topological defects:= You can also place wilson lines inside of the cobordism. These are 1D curves, and the idea is that you work with boundaries that are allowed *marked points* (the end points of the wilson lines.)


*** Chern-Simons

Consider a theory with $M = \Sigma \times \mathbb{R}$. We write

=Phase space:= Ends up being the moduli space of flat connections on $\Sigma$ modulo gauge transformations, which is finite-dimensional.

=Geometric Quantization:= We want to quantize this classical phase space. We pick a [[id:21b669d8-5f1a-4f81-b2ad-e5593eb97239][complex structure]] on $\Sigma$, turning it into a *Riemann surface*. The moduli space becomes a *Kähler manifold*. The Hilbert space ends up being a 0-cohomology (sheaf cohomology) of moduli space.

=Kodaira Vanishing Theorem:= Tells us that in this case the higher cohomology is zero.

**** Wilson Loops

In the case that $M$ has no boundary, we get that $Z(M)$ assigns a number; this is the path integral

$Z(M) = \int e^{i S[A]} dA$

$Z(M) = \int \frac{\mathcal{D}A}{\text{Vol}(\text{Gauge})} \exp\left( i \frac{k}{4\pi} \int_M \text{Tr}\left(A \wedge dA + \frac{2}{3}A^3\right) \right)$

When $M = S^{3}$, we get the topological invariant of the sphere. 

This is the vacuum expectation value. But we can also look at higher correlation functions. This is where the Wilson loops come in:

Start with a knot $K: S^{1} \rightarrow M$ and a finite-dimensional representation of the gauge group, $\rho$. The corresponding *Wilson loop operator* is defined to be

$W_{\rho} (K) = \text{Tr}_{\rho} [ \mathcal{P} \exp (\int_{K} A)]$.

where $\mathcal{P}$ is the path-ordering operator. The matrix $U(K) = \mathcal{P} \exp (\int_{K} A)$ is called the *holonomy matrix.* 

Now, $\langle W_{\rho}(K)\rangle$ is a topological invariant.

Now instead of looking at this correlator, we can instead change our space $M$, so that it *contains a hole / defect* --- that topological defect is its boundary, and it's precisely the knot $K$ that we want to take the correlator of. We can think of it like a tunnel through the sphere $S^{3}$.

**** Jones Polynomial

In the case $G = SU(2)$ and $\rho$ is the fundamental representation, you get the Jones polynomial *skein relation* being satisfied by the Wilson loop correlator.

** Donaldson-Witten

We consider *anti-instantons* $\star F = - F$.

We find that the moduli space of these anti-instantons is *non-compact* 

=Uhlenbeck compactness:= Donaldson used this compactification to try to compute integrals on the moduli space.

=Supersymmetry:= This is actually the *high energy limit* of $N=2$ supersymmetric Yang-Mills.

** Seibrg-Witten

We pick a spin structure on a 4-manifold with positive spinor bundle $S$ and determinant line bundle $L = \det(S)$. The fields are a $U(1)$ connection on $L$ and a positive spinor $\psi \in \Gamma(S)$.

Turns out, the *moduli space is compact* 

=Supersymmetry:= This is actually the *low energy limit* of $N=2$ supersymmetric Yang-Mills.

*** Gromov-Witten

When $M$ is a symplectic 4-manifold, the Seiberg-Witten invariants are equal to the Gromov-Witten invariants obtained from counting pseudo-holomorphic curves.

* Ultraviolet Divergence

Generally, in local quantum field theories, we have that the two-point correlator behaves like

$\langle \phi(x) \phi(y) \rangle \sim \dfrac{1}{| x - y|^{d-2}}$

This creates an *ultraviolet divergence* when we try to bring the points together. 

Also, when you try to construct a Hilbert space, you find that it can't be finite-dimensional: 

** Chern-Simons

We don't have a metric in Chern-Simons thory, so we can actually avoid this UV problem. This allows us to get finite-dimensional Hilbert spaces and have *extreme locality* --- this is where the *Cobordism Hypothesis* comes in
- because we can chop things up into arbitrarily small points, the full topological quantum field theory ends up being completely determined by what happens on a single point.


** UV Finite

In the case of theories that we can make UV finite, we can also get something like the cobordism hypothesis

Witten used a topological twist:

=Topological twist:= 

What ends up happening is that the physical observables end up being /metric independent/ 
