:PROPERTIES:
:ID:       f51e858b-d9da-48c6-99bf-17adbf093b33
:END:
#+title: algebraic quantum field theory
#+filetags: :math:aqft:

* References

* Summary

* C-star Algebras

These are not monoids in a monoidal category. But they are the traditional, physics-style AQFT observables.

So mathematical AQFT is unable to distinguish C-star algebras from Banach algebras.
- they miss the analysis / geometry

The same thing happens with von Neumann algebras.



* Double Categories

Speaker: Khyathi Komalan

One category version
Reg(M) is the category whose objects are regions and morphisms are inclusions
Codomain is von Neumann algebra with unital *-homomoprhisms

What if we also want embeddings that aren't inclusions? Like translations

double category of spacetime is same objects and inclusions are tight maps, embeddings are loose maps
squares have to commute

von Neumann algebras has ordinary stuff as tight maps and L^2 corresp as loose maps, and squares are intertwiners
T(a\zeta b) = f(a)T(\zeta) g(b)

then a pseudo double functor is a double-category AQFT

the tight restriction is the ordinary aqft
