:PROPERTIES:
:ID:       d9266e59-b649-4c42-895f-e664d85d21ea
:END:
#+title: conference notes
#+filetags: :math:conferences:presentations:

* References

Hi Chelsea,

I absolutely loved your talk yesterday! I looked up your website afterwards and was pleasantly surprised to find out you're from Detroit: I'm from Windsor. My research is actually focused on the relationships between Frobenius and Hopf algebras, so you can imagine I'm quite looking forward to volumes 2 and 3 of your Symmetries of Algebras series!

Anyway, I had some thoughts about possible approaches beyond the A_n and B_n cases you outlined - I'm not sure if they'll be any help, but here's what I was thinking:

I'm coming at this from a Lie algebra perspective, and so I immediately want to look at Coxeter groups in terms of root systems and the bilinear form $\langle x_i, x_j \rangle = - \|x_i \| \| x_j \| \cos(\pi /m_{ij})$. In the case of A_n, you can take the geometric realization of the root system, embeding it in $\mathbb{R}^{n+1}$: you take an orthonormal basis $\{ e_{i} \}$ and define $x_{i} = e_{i} - e_{i+1}$. Then the standard bilinear form on $\mathbb{R}^{n+1}$ will recover the Coxeter bilinear form up to a scalar. Then I want to say that this is somehow saying that $x_{i}$ corresponds to a braiding of strings $i$ and $i+1$ (moving vertex $i$ over and $i+1$ under, say ).

Fascinatingly, the same approach works for the case of $B_{n}$: your embedding has a series of terms of braiding-shape, $x_{i} = e_{i} - e_{i+1}$ for $1 \leq i \leq n-1$ and then a single string (wall) $x_{n} = e_{n}$. 

For the case of $D_{n}$ you get $x_{i} = e_{i} - e_{i+1}$ for $1 \leq i \leq n-1$ and $x_{n} = e_{n-1} + e_{n}$, I believe, which I'd like to say is 

The exceptional Coxeter groups are all fascinating, because you end up with strange things like $x_{1} = e_{1} - e_{2}$ and $x_{2} = -2 e_{1} + e_{2} + e_{3}$ for the case of $G_{2}$

* Chelsea Walton



quantum yang baxter
quantum reflection equation
R_1_2 K_1 R_2_1 K_2 = K_2 R_1_2 K_1 R_2_1

K_i is a reflection of particle i against the boundary

brochier (2013) - braided c-module category
(actegory)

the braiding of the action is the reflection
$\sigma : X \cdot M \rightarrow X\cdot M$

coxeter groups have graphs associated to them

type A gives you yang-baxter
and so correspond to braided monoidal categories

type B has a single reflection and corresponds to these braided c-module categories



quasitriangular hopf algebras
its modules become braided monoidal categories

braided morita equivalence
between quasitri hopf algebras
the equivalent is if their (H,R)-mod categories are equivalent

thm shimizu 2010
braid group represents gives braided morita invar

if braided morita equivalent then represents of braid groups are isomorphism

other side

quasitri h-comodule  algebra

the category of mods is a c-mod category
to make it braided, you need a K-matrix (like the R-matrix)

you get a braided morita equivalence

fd quasitri coideal subalgs that are braided morita equivalent gives equivalent of represents
** Categorical Centers

for yang baxter
take a monoidal category, you get a braided monoidal category 
- take the drinfled center
- the drinfled center is braided morita equivalent to the drifeld double modules category (in the fd case)

for the reflection pic
laugwitz-walton-yakimov (2025)
- reflective center
- the reflective algebra is the thing corresponding to the drinfeld double

throw in ribbons and you get modular structures
** non degeneracy

given a finite tensor braided monoidal category

non deg means that the drinfeld center factorizes
- ex factorizable hopf algebras

equivalent to a center coend being an actual hopf algebra with a non-degen laplace pairing

[shimizu 2019]

the reflective case
- the end has a certain non-degen pairing
- equivalent to being factorizable

future work: quantum group versions of these reflective things
** Speculations

look at all the coxeter types
- can you always represent these with string models?

- what's the categorical version?

- is there a physics version of each of these?

- is there a single equation that specializes to yang baxter and the reflection
* Augustina Czenky 

Tensor categories are the pre-categories of modular tensor categories

You want both an abelian and a monoidal structure

Homs are finite-dimensional  vector spaces.

You want to be rigid: Duals exist

And you need the endomorph of the unit are the base field (aka the unit is simple)

For a mondular category you need
- a braiding

fusion categories are tensor categories with
- the category is semisimple
- the category has fin many simples
- the rank is defined to be the number of simple objects

A pre-modular category is a ribbon braided fusion category
- the ribbon is a certain collection of endomorphisms $\theta_{X}: X \rightarrow X$ for all X
- you can define an *S-matrix*
- S = Tr(\sigma_X_Y \sigma_Y_X) with X,Y simple

If the S-matrix is invertible, you get a *modular cat* 
** Example

Tambara-Yamagami

You start with a finite abelian group and take a symmetric bicharacter
- this should be a laplace pairing on kG

The simple objects are the elements of G along with one additional object

Fusion rules
$a \otimes b = ab$
a \otimes x =x \otimes a = x
x \otimes x = \oplus_a_\in_A a

If the order of the group is odd and the bicharacter is non-degen you get a unique modular structure
* Problems

Classification: organizing what we know
- rank finiteness conjecture (2013)
- only finitely many modular categories of a fixed rank

Construction: new from old

Frobenius-Peron dim
- if 1 you're called pointed
- if Z you're equivalent to representations of a quasi-hopf alg

For fusion categories, classification by rank is very hard
- only done up to rank 2

For modular categories 
- if fp dim is odd then we know the case of rank \leq 11
       - you're pointed (classified by group data)
- in general we have classification up to rank 12


Question: Can you find odd FP-dim MTC which is perfect (only invertible object is the unit)?
- this is very difficult, but people think the answer is no

perfect: evaluation and coevalution are isos

** Future directions

non-algebraically closed field
char p
non-semisimple case

* Marino Gran

Hopf formulae for cocommutative Hopf algebras

Semiabelian categories
- non-abelian homological algebra.

Def: finitely complete category with
- 0 object
- binary coprods
- Barr-exact (factor as regular epi followed by mono)
       - regular epis are pullback stable
- bourn-protomodular

The canonical morph from coproduct to prod is not an isomorphism

** Hopf Algebras

Take cocommutative hopf algebras. 
- ex group algebra
- symmetric algebra
- tensor algebra

The category of cocommutative Hopf algebras is semi-abelian 
- it's also strongly protomodular

The category of commutative and cocommutative Hopf algebras is abelian


In groups, free resolutions' second homology has a hopf-formula

** Galois Theory

You want to view a Hopf algebra as a quotient of some projective resolution and then take the universal central extension

You get a galois groupoid

** Yang Baxter

A skew brace gives you bijective solutions to YB
