:PROPERTIES:
:ID:       589d1426-d6a5-47df-995b-b395fae2029d
:END:
#+title: topological vector spaces
#+filetags: :math:func_analysis:

* References 

* Summary 



* Initial Topologies

** Lemma

: If {f_i : X \to X_i} are linear then initial top is TVS

: If X_i are locally convex then so is X



** Lemma

: If {f_i: X \to X_i} gives initial top then
: g:A \to X is cont iff g f_i cont \forall i

: Moreover, initial top on Y wrt g is the same as wrt {g f_i}


** Lemma: Subfamily

: If F \sube G is a subfamily of generating maps then
: I_F \sube I_G
: where I denotes the initial topology.

The topology from G has as open sets all g_i^{-1}(U) where U is open
For those f \in F, their open sets will also be open in G. So G is finer

*** Reverse

In order for the reverse to hold, given an open set U_G in I_G, we need we need an open set U_F in I_F with U_F \sube U_G



*** Frobenius Algebra

In order to remove <-,z> from our generating set, we need

Given any U and {x | <x,z> \in U} there is some w and V with
{x | <x,w> \in V} or {x | <w, x> \in V} \sube {x | <x,z> \in U}

We can always restrict to a basis. So say we look at
{x | |<x,z>| < r}

We can take <-, \lambda z> for *any \lambda* \ne 0 and look at
{ x  | |<x,\lambda z>| < |\lambda| r }

That's actually very helpful, because it means that we can take as our generating set a kind of projectivization

But we can actually just reduce to the *basis elements*
So we pick a basis {b_i} (possibly infinite-dimensional)

Write z = \alpha_1 b(i_1) + ... + \alpha_n b(i_n)
Then |<x, z>| \leq |\alpha_1| |<x, b(i_1)>| + ... + |\alpha_n| |<x, b(i_n)>|

Now the \alpha and n only depend on z and are thus fixed. So we just take the intersection of the open sets defined by each { x | |<x,b(i_k)>| < r / (n \alpha_k) }



* Strong/Weak Topologies



** Weak Topology

: Def : Given any TVS V, we can define an initial topology generated by all of the *continuous linear functionals*

: This is called the *weak topology* of V.

If we want to talk about topological properties with respect to this topology, we'll call them

**** Prop: There are no new continuous linear functionals

Let <-,->: V \times W \to k be a bilinear form (not-necessarily non-degenerate)
Let V have the initial topology generated by all <-,w>: V \to k
Let \phi : V \to k be a cont linear functional
Then there is some w \in W such that \phi = <-,w> 

:CONJECTURE:



Is it true that if we take <-,->: V \times V \to k and both <-,x> and <x,-> as generating the initial topology, we don't get any more continuous linear functionals?

If we take that topology, we've added extra generating functions, which will make more maps continuous, and thus 


:END:

*** Frobenius Algebra

So a Frobenius algebra F will have its Frobenius topology, generated by the <x,-> and <-,x>. But it will also have a weak and strong topology.

But by the above proposition, F has no continuous linear functionals that aren't of the form <-,x>

** Strong Topology

* Semi-norms

: Def : p(x+y) \le p(x) + p(y)
:       p(\lambda x) = |\lambda|p(x)      


To be a norm, we also need p(x) = 0 implies x = 0

**** Lemma: Absolute value doesn't change anything

: Given linear functionals f_i : X \to k, the initial topology generated is the same as the initial topology generated by |f_i|: X \to R

Basically you use the fact that the absolute value | \cdot | : k \to R is continuous for both k = C and R. So you use the fact that the initial top on X \to V \to V_i is the same as the initial top from X \to \v

Given any bilinear form <-,->: V \times W \to k
The initial topologies generated by <-,W>: V \to k and <V,-> : W \to k
are also generated by post-composing with the absolute value


*** Frobenius Algebra

Any unital Frobenius algebra will have its topology generated simply by \varepsilon
since 




** Semi-norm Initial Topology

The SN topology for a family of seminorms is the initial topology with respect to them
This *is not* necessarily a TVS structure, since the seminorms aren't linear maps and don't necessarily come from linear maps





* Special Subsets

** Absorbing

: Def : Let U \sube V
: For all x there is some \alpha > 0 with x \in \lambda U for all |\lambda| \geq \alpha

This says that given any element x, if we expand U, it will eventually contain x.

*** Frobenius Algebras

U = { x | <x,x>  }


** Balanced

B is *balanced* if \lambda B \sube B for all |\lambda| \leq 1

*** Frobenius Algebras


** Barreled

B is a *barrel* if it is
1. Convex
2. Balanced
3. Absorbing
4. Closed

A *barrelled space* is a TVS for which every barrel is a nbh of zero.   

*** Frobenius Algebras



** Bounded

B is *bounded* if for all zero nbh U, there is a \lambda such that B \sube \lambda U
This is equivalent to for all zero nbh U there is an \alpha with B \sube \lambda U for all |\lambda| \geq \alpha

In other words, every zero nbh absorbs B

The finer the topology, the *fewer* bounded sets (because they have to satisfy more conditions)

In a LCTVS, B is bounded iff every countable subset A \sube B has p(A) bounded for all p

**** Prop

Continuous functions between TVS map bounded to bounded

**** Prop

For an initial topology generated by f_i: V \to V_i, B is bounded iff f_i(B) is bounded \forall i

**** Prop
B is bounded iff for any sequence b_n \in B and scalars \lambda_n \to 0, we have
(\lambda_n b_n) \to 0

**** Prop

Let <E,F> be a dual pair
A polar A^\circ is absorbing iff A is bounded


**** Prop: Preserving Boundedness

If B is bounded then so is

1. The convex hull (in a LCTVS)
2. The closure
3. Balanced hull
4. Absolutely convex closed hull (in a LCTVS)

*** Frobenius Algebras


** (Totally) Bounded / Precompact

B is precompact if for any nbh of zero, U, there is a finite set of translations of U, {a_i + U} which covers B

**** Prop

Closed under
1. Convex hull (LCTVS)
2. Closed absolutely convex hull (LCTVS)

**** Prop

Compact iff precompact and complete





** Closed

A linear function on a TVS is cont iff ker f is closed.

** Convex

C is *convex* if \lambda x + (1 - \lambda)y \in C for all x,y \in C, 0 \leq \lambda \leq 1

**** Prop: LCTVS, you get convexity for free on bounded sets

In any LCTVS, convex hulls of bounded sets are bounded


**** If C is convex then so is both Int(C) and Cl(C)

*** Frobenius Algebras



**** Prop

Let C be convex in a LCTVS, then C is closed iff C is weakly closed

** Polar

* Topological Vector Spaces


** Proposition: Continuous Operations

: Let V be a TVS
:
: x \to x + y is a homeo
: x \to \lambda x is a homeo
: \lambda \to \lambda x is cont
:
: every (not nec open) nbh of zero is absorbing
: every nbh U has some W with W + W \sube U


For the absorbing one, we take the map f: \lambda \to \lambda x
For any nbh of zero, U, and any x, we take the preimage of this map, f^{-1}(U). Now \lambda \in f^{-1}(U) iff \lambda x \in U iff x \in \lambda^{-1} U.
Since f(0) = 0 \in U, we can take a small ball in f^{-1}(U) around 0, with radius less than 1. Call the radius \alpha

Then you're inside this ball iff |\lambda| < \alpha




The last one follows from continuity of addition
In particular, we're cont at (0,0) in V \times V
0 + 0 = 0, so we take a nbh around 0, U, preimage from addition to get a nbh of (0,0). Restricting to a basic nbh we have A_1 \times A_2 with
A_1 + A_2 \sube U
Now set W = A_1 \cap A_2

* Locally Convex TVS






** Continuity

: If V's topology is defined by a family of seminorms, then
: x_\alpha \to 0 (as a net) iff each p(x_\alpha) \to 0



Given two LCTVS a map between them f: V \to W is cont iff
for each seminorm p_W, there is a finite number of q_V^i and a constant \alpha_P such that
p_W(f(x)) \le \alpha_P (q_V^1(x) + ... + q_V^n (x))
for all x

*** Frobenius Algebra

The topology on F \times F is induced by the projections followed by the pairing
So
(x,y) \to <x,z>, <z,x>, <y,z> or <z,y>
for a fixed z.

So the pairing is jointly continuous iff there is some C such that
The map |<x,y>| \le C (q_1(x,y) + ... + q_n(x,y))
for all x,y


** Frobenius Algebra

The topology induced by <-,-> : F \times F \to k
has as a basis of open sets for the origin

{x | |<x,b_j>|, |<a_i, x>| < r}     where {a_i, b_j} is a finite set of elements of F

In other words, you take a finite number of the generating seminorms, and some radius



** Set Types

For any seminorm, {x | p(x) < 1} and {x | p(x) \leq 1} are
1. Convex
2. Absorbing
3. Balanced


B is bounded iff each p_\alpha(B) is bounded in R






* Locally Bounded Maps

A locally bounded map f: V \to W is one which sends bounded sets to bounded sets.

* Continuity

A linear map between TVS f: V \to W is cont iff it is cont at any single point

A continuous linear map is uniformly continuous.

A map f: V \to k is cont iff there is a cont seminorm on V s.t. |f|\le p

A map f: V \to k is cont iff the kernel is closed

*** Frobenius Algebra

<-,-> : F \times F \to k



* Convergence

Let V be a LCTVS defined by seminorms {p_\alpha}
A net (x_\alpha) \to x iff p(x_\alpha - x) \to 0 for all p


* Universal Constructions


** Products

Arbitrary products of LCTVS are still LCTVS.
The seminorms are the projections followed by the original seminorms

\prod_\alpha V_\alpha \to V_\beta \to k
