:PROPERTIES:
:ID:       fdde2b71-a9d9-4ed5-97e5-b6d89e128b50
:END:
#+title: chain complexes
#+filetags: :math:homotopy:homology:cohomology:

* References




* [[id:af6e1442-858e-42ec-93aa-b4d5a31dd28a][(co)Homology]]


* Exact Sequences

From our discussions on homology, we have that exact sequences are like spaces that are *very calm*
- no singularities
- no holes
- no vortices

But they can still have twists (like a Möbius band)  

** Split Exact Sequences

Correspond to untwisted, calm spaces.

* Summary

Consider a polynomial algebra k[x]. We can perform a resolution on the algebra k[x]/x
- We want k[x]/x to be the zeroth homology, and for all the other homologies to be zero.
  
Set C_0 = k[x] and C_1 = k[x, \varepsilon], where \varepsilon is a formal element in degree 1, and defining
d(\varepsilon) = x.

If we further require the algebra structure to be graded commutative, we have
\varepsilon^2 = 0.
So we can interpret this as something like an *infinitesimal*

Now the elements in degree 1 have the form
p(x) \varepsilon , where p(x) \in C_0 is a polynomial
with boundary
d(p) \varepsilon + p d(\varepsilon) = 0 + p(x) x.

It follows that if there is a cycle in degree 1, we'd have
d(p \varepsilon) = p(x) x = 0.

If there are no zero-divisors, this implies that there are no cycles. So
H_1 \cong 0.

Similarly, if we take the higher degrees, we're trivial, because they would need to be built out of elements in degree 1 (to increase the degree). But since \varepsilon^2 = 0, this produces no elements above degree 1. Thus
H_{n \geq 1} \cong 0,
and so we get a (very easy) resolution of k[x]:
0 \to k[x, \varepsilon] \to k[x] \to 0
which is quasi-isomorphic to k[x] (as a trivial chain complex: 0 \to k[x] \to 0).

* Functional Analysis

** Fredholm Operators

By definition, these are operators with
- finite dimensional kernel
- finite dimensional and closed cokernel

The *Fredholm index* is
    dim(ker) - dim(coker)
It counts solutions to equations

** Atiyah-Singer Index Theorem

If T is an elliptic differential operator on a manifold, the analytical index is equal to the topological index
- the analytical index is the homology of the operator
- the topological index is the cohomology of the manifold's tangent bundle.

* Harmonic Analysis

A locally compact group is amenable if and only if its first Hochschild cohomology group of its convolution algebra with coefficients in dual modules is zero:
       H^1(L^1(G), X^*) \cong 0

* Complex Analysis

** Hartog's Extension Theorem

Holomorphic functions are those that are locally complex differentiable
- each point has some neighbourhood on which it's complex differentiable.

This is enough to conclude that the function is analytic  

*** Sheaf Cohomology

** Analytic Continuation

This is actually related to *relative cohomology*

Mikio Sato viewed real functions (which you'd like to analytically continue) as /being boundaries between two holomorphic functions/

You build relative cohomology out of this idea: take
... \to O(C) \to O(C \setminus R) \to H^1_R(C, O) \to 0
where O is the sheaf of holomorphic functions.
This is a long exact sequence.

An element of O(C \setminus R) is really a pair of holomorphic functions: one defined on the upper half plane, one defined on the lower.

The codifferential into H^1 is a computation of the difference between a pair of holomorphic functions, as you approach the real axis.

Functions that admit analytic continuations are precisely coboundaries in the first degree

** Wick Rotation

When you take a path integral, say over time, you're integrating
\int_{-\infty}^{\infty} \omega
where \omega is some complex differential form.

When we do wick rotation, we want to switch into imaginary time. How does this work?

Consider the upper right and lower left quadrants of the complex plane.

Well say \omega is closed (a cocycle). Then we can think of the real and imaginary axes as two half-coverings of a larger bulk made up of the upper right and lower left quadrants
- if there are no poles in those quadrants, then we can perform wick rotation, because our two different half-coverings give the same integral.

To be a bit more precise, typically what you do is you have to consider finite parts of the quadrants and then take the limits to infinity
- this is because the integral over the whole, non-compact, domain might not exist

  On the other hand, you can use *Borel-Moore Homology*
  - this allows your chains to be non-compact.
  - it'll basically give you exactly what I was saying above

I guess another way of thinking about it, is you compactify C (say, into the Riemann sphere) and then play the game
- the real and imaginary axes become circles on the sphere that meet at 0 and \infty (north and south poles)
 But when you do this, your integrand actually becomes very messy at \infty
 - but you can't just remove that point, because it'll add a new point to your boundary
- so you basically turn the point into a small circle and then take the limit as you close the circle

If the pole at \infty is regular or logarithmic, everything is fine
- if it's an essential singularity, you have to be careful
- this is actually related to *global D-Module theory*

* Cup Product


