:PROPERTIES:
:ID:       ee30063a-52c7-41d2-9051-e819e8262730
:END:
#+title: d modules
#+filetags: :math:geometry:

* References



* Summary

Basically D-modules are the differential operator analogue of affine varieties. Just like how a variety is the quotient of an algebra by some collection of polynomials, D-modules are quotients by collections of differential operators.

=Linearity:= D-modules can only handle *linear pdes* 

=Global:= Traditional analysis of PDEs has difficulty with extending solutions globally on a manifold, because it tries to find explicit solutions. One way of fixing this is to use *sheafs of D-modules*; that way, you don't have to rely on finding any explicit formula. 

=Riemann-Hilbert:= This theorem tells you that certain linear PDE systems (holonomic with regular singularities), the solution space is determined by its *topological data*. This allows you to replace a PDE by a *perverse sheaf* and study the perverse sheaf instead. 



=Characteristic variety:=  

=Monodromy:= 

=Localization:= Representations of Lie algebras turn out to be the same as D-modules on flag varieties.

** Non-linear Problems

*** General relativity

*** Non-linear optics

High-intensity lasers change the refractive index of the medium they're travelling through 

=Quantum gravity:= Should behave somewhat like non-linear optics --- the energy of particles should alter the spacetime background 

*** Chaotic systems

*** Fluid dynamics

**** Navier-Stokes

D-modules weren't directly applied to Navier-Stokes for a few reasons: most obviously, because the NS equations are non-linear. 

More importantly, D-module theory only tells you if solutions exist /formally/, not whether those solutions are /stable/ 

* Definitions




* Theorems

** Riemann-Hilbert correspondence

A holonomic D-module with regular singularities is equivalent to a representation of the fundamental group

** Beilinson-Bernstein localization


* Examples

** Weyl algebra

Let \(A_{n}(k)\) be the Weyl algebra in \(n\) dimensions over the field \(k\)

An example of an algebraic D-module on \(\mathbb{C}^{n}\) is a left \(A_{n}(\mathbb{C})\)-module.

If we take some system of equations that we want to investigate, we consider the ideal they generate, \(I\), and then take the quotient
\[
A_{n}(k)/I
\]

Now let's say that we want to find solutions to the equations in some space of functions \(F\) on which the Weyl algebra acts (ie on some D-module). We just look at \(A_{n}(k)\)-module maps
\[
A_{n}(k)/I \rightarrow F
\]

*** Solutions

The quotient \(A_{n}(k)/I\) is actually generated by \(1 + I\), since any \(x + I = x (1 + I)\). So given a map \(\phi: A_{n}(k)/I \rightarrow F\), we have 
\[
\phi(x+I) = \phi(x (1 + I)) = x \phi(1+I)
\],
using the fact that this is a morphism of \(A_{n}(k)\)-modules. 

Now, taking \(x \in I\), we must have \(\phi(x + I) = \phi(0 + I) = 0\), so 
\[
x \phi(1 + I) = 0
\]
for all \(x \in I\).

So the choice of image of \(1 + I\) corresponds to a *solution* to the system of equations captured by \(I\).

** Structure sheaf

** Delta function

** Integrable connections

** Global D-modules

We replace the Weyl algebra by a *sheaf of differential operators* 

** Free quantum field theory 

\[
A_{n}(k)/\langle \partial^{2} + m^{2} \rangle
\]
