:PROPERTIES:
:ID:       08cefc36-d4a7-4987-8622-b2a36204b4a6
:END:
#+title: measure theory
#+filetags: :math:

* References



* Summary

There are some spaces that even manifolds can't keep track of; this is mainly where Lebesgue integration comes in.

This leads to things like dominated convergence. 

Oh here's a fascinating thing I just learned: in undergraduate vector calculus, we have formulas like 

\[
\int_{\gamma} f = \int_{a}^{b} f(\gamma(t)) |\gamma'(t)| dt.
\]

\[
\int_{\gamma} F(\gamma) \cdot d\gamma = \int_{a}^{b} F(\gamma(t)) \cdot \gamma'(t) dt.
\]

This is actually a *measure-theoretic integral*, not a calculus on manifolds one. This starts to explain why I have difficulty understanding how differential forms fit into vector calculus. The calculus on manifolds set up is where you deal with the formal calculus of differentials; so in that case you're working with things like \(P dx + Q dy.\) The problem, I'm now realizing is that my professors would jump back and forth between these two paradigms, without making it clear what they were doing. 

How can you tell when it's a measure-theoretic integral? Whenever it has an aspect that depends on coordinates --- dot products, norms --- it's measure theory.

* Definitions

** [[id:b3a45b17-d5f0-427e-b60a-6913c0a6d3cc][sigma algebra]]

** Measure

* Outer Measure

\lambda^*(A) = inf { \sum_i \ell(I_i) | A \sube \cup_i I_i   }

where I_i are intervals and \ell is their length

Replacing the sums by finite ones gives the *Jordan content*
- it's not countably additive


* Theorems


** Banach-Tarski paradox

* Examples

