:PROPERTIES:
:ID:       410b1a4a-6cf2-4051-ae04-d397a654ab4a
:END:
#+title: representation theory
#+filetags: :math:area:

* References


* Summary

* Definitions

A representation of a group $G$ is a group homomorphism
G \to Aut(V) = GL(V)
into the automorphisms on a vector space. This is equivalent to saying that it's the structure of a kG-module on a k-vector space V.
- in other words, G acts on V

A unitary representation is a representation that maps into the unitary operators on a Hilbert spaace
G \to U(H)
We view \mathbb{C} G as an involutive structure, with (\lambda g)^* = \lambda^* g^{-1}. Then a unitary representation is a \mathbb{C} G module with an inner product such that
<g x, y> = <x, g^* y> for all g \in kG
In other words, V is a *-representation.

** Reducibility

*** Irreducible

An irreducible representation is a representation such that there are no subspaces of V invariant under the action of G.
From the module perspective, it's the same thing as a simple kG-module.

*** Completely Reducible

V is a direct sum of irreducible representations

V is a semisimple module

** Regular Representation

Or G acting on functions f: G \to k via left multiplication

kG acting on itself

** Characters

The trace of the representation matrix
\chi(g) = Tr(\rho(g))

A linear functional on kG from the trace of the endomorphism representation, vanishing on the commutator subspace [kG, kG]

Class functions (constant on conjugacy classes) are equivalent to the center Z(kG)

Irreducible modules correspond to ring maps Z(kG) \to k

*** Linear Functionals and Integrals

When we look at characters as linear functionals on kG, we can view them as corresponding to integrals; in particular, they correspond to *integral kernels*

This is particularly useful when we look at characters for infinite groups

*** Irreducible

If V is an irreducible representation, we define the specific character
\chi(g) = Tr(\rho(g))
as the irreducible character of this representation

Irreducible characters end up being equivalent to maps G \to \mathbb{C} such that

1. It's a class function
2. <\chi, \chi> = 1
3. <\phi, \chi> \geq 0

From the module perspective, an irreducible character is a linear functional if and only if

**** U(1) : One-dimensional Irreducible Unitary

The 1-dim irreducible unitary characters are exactly maps into U(1)

*** Inner Product on (kG)^*

We can define the inner product as a Frobenius pairing, where we take kG as the coalgebra with duplication coproduct, giving (kG)^* an algebra structure. Then we can take the counit to be the average over the group if it's finite
- for compact groups, you use the Haar measure and take L^2(G) instead of the strict dual

- locally compact groups also have a Haar measure, but the integral over the whole space is infinite
       You have a few options:
       1. the Plancherel Theorem gives us a measure on the space of irreducible representations (the *spectrum* of the group), and you integrate over this
       2. you essentially restrict to Schwartz-like functions and use temmpered distributions. The tempered distributions don't have an inner product though. So you have to use a Fourier transform on them to map them back into L^2(spectrum)

- non locally compact groups are difficult:
       - since there's no Haar measure, by definition there's no translation-invariant measure
       - so you use a quasi-invariant measure: actions by the group elements preserve null sets
       - you then define a Radon-Nikodym derivative \rho(g,x) = \dfrac{d g_* \mu}{d \mu}(x)
       - and define a unitary action on L^2(G, \mu) with (U(g) \cdot f) (x) = \sqrt{\rho(g,x)} f(g^{-1} x)
       - and you integrate with respect to the quasi-invariant measure

         An example of this is the *Wiener measure*!

Another solution is to take the colimit of compact subgroups
G^\bullet = \colim G_1 \leq G_2 \leq ...

Then you take the limit over the the haar measures (when this exists; which is only for certain characters)
<\phi, \psi> = \lim \int_{G_n} \phi(g) \psi^*(g) d \mu_n(g)

*** Orthogonality

Over \mathbb{C} we have that the irreducible characters satisfy

<\chi_i, \chi_j> = \dfrac{1}{|G|} \sum_g \chi_i(g) \chi_j^*(g) = \delta_{ij}

This allows us to decompose an arbitrary complex representation into irreducible pieces using projection

From the kG-module perspective, we have Wedderburn's Structure Theorem



* Theorems

** Maschke's Theorem

*** Intuition

If G is a finite group and 

*** Statement

Let G be a finite group with |G| \nequiv 0 (mod char k), and let V be a representation.
Then every invariant subspace W \subseteq V has a complement subspace U with
V = W \oplus U

From the module perspective, this says that every finite group with |G| \ne 0 (mod char k) has kG semisimple.

Every short exact sequence of kG-modules splits

** Schur's Lemma

*** Statement

Let \phi_1, \phi_2 be irreducible representations on V_1 and V_2, and let \Psi: \phi_1 \to \phi_2 (commutative square)
Then

1. \Psi is an isomorphism or \Psi = 0.
2. If V_1 = V_2 and k is algebraically closed then \Psi = \lambda I for some \lambda \in k.

From the perspective of kG-modules we have

If V_1 and V_2 are simple kG-modules then

1. Hom_{kG}(V_1, V_2) = 0 if and only if V_1 \notcong V_2
2. If V_1 \cong V_2 then End_{kG}(V) is a division ring
        + If k is algebraically closed and V is finite dimensional, then End_{kG}(V) \cong k

          


