PXE (Preboot Execution Environment) Server


When you turn on a laptop

* OSI Model

Seven levels:
1. Physical
2. Data Link
3. Network
4. Transport
5. Session
6. Presentation
7. Application

* Network Interface Card (NIC) 

This is a hardware component of your computer --- it's what allows you to connect to a network

It converts data into EM signals
- either radio waves for wifi
- or electrical signals for wired

The NIC is responsible for the first 2 layers of the OSI model. 

** Memory

Most NICs have a small amount of *non-volatile memory*
- it stores the PXE firmware

/Network Boots/ tell the CPU to use the NIC's firmware, instead of the hardrive

** Direct Memory Access

The NIC receives a packet from the network, verifies the checksum, and drops it into RAM. Once enough data has been stored in RAM, it tells the CPU to process the data

** Promiscuous Mode

Tells the NIC to pass /every/ packet it sees to the CPU, instead of just the ones addressed to its MAC address.

** Serialization

Data from the CPU is taken and converted into a stream of electrical pulses or radio waves

** Media Access Control (MAC)

Every NIC has a MAC address burned into its ROM.
- this is a stable identification of the device

The NIC listens to the wire and if it sees information directed to its MAC address, it knows to react

* DORA Process

* DHCP

* TFTP

* HTTP 

* TCP/IP Stack (Internet Protocol Suite)

It tells computers how to interact over a network

It's made up of a bunch of layers (a stack)

1. Application
- how the user interacts with the network
- http, ssh, ftp, dns
- turns your data into a format that the network can understand

HTTP (hypertext transfer protocol)
- stateless
- request-response protocol

The browser sends a GET or POST request to the server
- the server looks for the corresponding file and sends it back *with a status code*
- 404 not found
- 200 OK

HTTPS uses TLS/SSL to encrypt the HTTP data

Uses port 443

Internet Service Providers use *caching proxies*: if someone else on th network downloaded something, the ISP will retain a local copy in its cache

HTTP is very lightweight

SSH (Secure Shell)

Used for remote *administration*
Creates a persistent, encrypted session.

Uses public/private keys
- when you connect to your device from another machine, the two devices do a /handshake/ to prove identities without sending an actual password

Once you have the SSH set up, you can send things through it
- the SSH gives you a shell that you can use to execute logic on the remote machine


DNS (Domain Name System)
When you type a URL, the system sends a DNS query for the corresponding IP address
- usually this is over *UDP port 53*

FTP/SFTP (File Transfer Protocol)

HTTP wasn't originally designed for file transfer; FTP was
- although actually you can use HTTP for file transfer

FTP is *stateful*
- the server remembers you as long as the session is open

Original FTP sends everything in plain text, while SFTP uses SSH

FTP uses 2 connections:
1. Commands
2. Data

There are some issues with FTP
- the two connections makes firewalls suspicious, unlike HTTP, which only uses one connection
- it uses a ton of RAM: every connection requires a unique handshake and keeps a persistent state on the serer. HTTPS can handle the request and then forget the client

Because FTP was designed for file transfer, it has built-in tools for things like
- setting up schedules (although HTTPS is used for that today too; you just get some other program to set the schedule and then use HTTP for the actual transfer)

Backing Up Files

Google Drive and Dropbox use HTTPS
- they use REST APIs over HTTPS and send POST and PUT requests

Private servers often use SFTP

You use SFTP when you already have a secure shell set up
- if you use HTTPS and SSH, it's actually *less secure*
- because they use different ports, you have a new place that hackers can attack
- SFTP uses the same port as SSH (port 22)

2. Transport
- TCP, UDP
- TCP breaks data into segments, numbers them and waits for an *acknowledgement* (ACK) from the receiver. If a segment is lost, TCP resends it
- UDP is faster than TCP, but less reliable: it sends data without checking that it ever arrived (ex. streaming music / videos)

Source Port: a random large number assigned by your laptop to keep track of an outgoing request

Destination Port: A /standardized/ number that tells the receiver where the received data belongs

There are 65,535 ports
- the first 1024 are reserved for things like HTTP, SSH, DNS
- then there are the *registered ports*, which are used by specific sofware companies, like MySQL or Steam.
- finally the dynamic/private ports

Sockets: are IPs + ports
- ex. 192.168.1.50:22 (SSH into a particular IP)

When you open different browser tabs, each tab gets its own port

Nmap Tool
- queries all of the ports to see which ones are open

Windows opens a bunch of ports by default, for things like Remote Procedure Calls (RPCs, port 135) and Server Message Blocks (SMBs, port 445)

RCP: when a program makes an RCP cal, the local system packages (*marshals*) the request, and sends it to the remote system. The remote system executes the task and sends the result back.
- ex. when Windows manages its services across a network
- this can be used by hackers for Remote Code Execution (RCE) 

SMB: The language that Windows uses for file sharing, printer sharing, ect. 
- lets applications read and write to files and request services from programs in a network
- ex. sending a document to a shared network printer
- SMBs are used to send RPCs.

Windows computers are *very noisy*
- they constantly send out SMBs and RPCs into the network, to see if there are printers, for ex.
- this causes Windows to be more resource intensive while idle than Linux.

EternalBlue was a powerful exploit of SMBs

SMBv1 driver (srv.sys)
- extended attributes are stored in two formats: OS/2 and NT
- the driver converts from OS/2 to NT

=SMB_COM_NT_TRANSACT= uses dwords, while =SMB_COM_TRANSACTION2_SECONDARY= uses words.
- 

Buffer Overflow

A buffer is a temporary storage area in RAM
Many old programming languages, like C and C++ don't actually check if data is small enough to fit in a buffer. If the data is too large, it /overflows/ into the neighbouring memory addresses.

The Return Address (RET) tells the CPU to return to the main program
- if we overflow and overwrite the return address, we can tell the CPU to return to *a malicious program*

Address Space Layout Randomization (ASLR)
Every time the computer boots, it randomizes its addresses. This makes it harder for an attacker to know the address of their malicious code
- if you can figure out the address layout before a boot happens, you can attack effectively
- you need an *information leak*: if you can find a single memory address, you can use that to find out where the shellcode is hidden

No Operation Sled (NOP Sled)
The shellcode has its first 1000 bytes NOPs; the malicious code is at the end. Then, if the return address gets changed to something that hits any of those NOPs, the CPU will slide along the address until it reaches the malicious code

Runtimes
Programming languages like Python and Java have this: it checks to make sure that there are no buffer overflows.
In a language like C, raw instructions are just sent to the CPU. The CPU doesn't know about buffers and their sizes, so it allows buffer overflows.

Garbage collectors are background processes inside of the runtime. They look for pieces of memory that the program is no longer using, to reclaim tem for future use
- reference counting: has a stack of references to each object. When a variable gets deleted, it gets popped from the stack; when the stack is empty, the object is considered garbage and is deleted
- but this can't handle circular references (the stack will never be empty, and you get a memory leak)
- mark-and-sweep: the garbage collector starts at the global variables and running functions and traces every pointer to see what it can reach. Everything it reaches is marked as live. Anything not marked it swept away from the memory.
- GCs make sure that memory is only freed once you're no longer going to use what it's currently housing

Runtime Bounds Checking: this is what handles buffer overflows
- in something like python, you don't access memory directly
- instead, you work with objects, like arrays
- if you try to write to an array, the runtime will check if you're able to do that without causing a buffer overflow; if not it gives you an error like IndexOutOfBounds

But *Python is written in C*
- so you can actually attack the python interpreter (cpython), or the underlying C libraries in python (ex. OpenSSL)

Memory-Safe Systems Languages
Things like C --- very low level --- but memory safe
- ex. Rust: it tracks every variable and knows when it's no longer needed. Rust refuses to compile a program if there's /a chance/ of a buffer overflow or memory leak. But it doesn't need to use a Runtime like python.

Resource Exhaustion (DoS)
Regex DoS (ReDoS): the attacker sends a string to a regex checker that has exponential growth

Data Execution Prevention (DEP/NX)
Marks the buffers as *non-executable*

Return-Oriented Programming (ROP)
Instead of injecting their own code, attackers stitch together pieces of legitimate code in a computer's memory to perform an attack

Heap Grooming/Spraying


3. Internet
- IP addresses
- IP, ICMP
- packages segments into *packets* and adds the source and destination IP addresses
  
4. Network Access
- the hardware
- NIC and ethernet cable
- converts IP packets into *frames* and then into electrical or radio signals
- uses MAC addresses to move data between two pieces of hardware on the same local network.


