:PROPERTIES:
:ID:       98aa0bbb-4931-4d51-9ff1-2442f2d16c0d
:ROAM_ALIASES: "canadian economic history"
:END:
#+title: canada economic history
#+filetags: :Economic History:

* References 

Bank of Canada press releases


* Summary 

* History

Looking at the BoC policy rates over the years, let's see if we can spot any patterns:

Prior to 1997, the BoC tried to do quantitative easing to offset effects of private and public sector restructuring

(below I'm using the policy rate, which is 1/2% lower than the Bank Rate most of the time)



** 1985

*** [[id:3dfb6d40-b083-4ba4-9102-84acc5ce0ff9][Plaza Accord]]

American dollar depreciates

** 1991

Government and Bank of Canada announce targets for reducing inflation, with the goal of reaching 2% by 1995

** 1993

Bank of Canada sets up goals to keep inflation around 2% until 1998

** 1997

June 3%
Oct 3.25%
Nov 3.5%
Dec 4%

Weakness in Canadian dollar against the US and other currencies
- increasing the interest rate is meant to counteract this
- Canadian interest rates were lagging behind the US, contributing to the weaker dollar
  
Canadian economy growing quickly with low inflation

*** [[id:9e2eb54f-e86d-4bdb-8577-f63a91074ab6][Asian Financial Crisis]]

Issues in Asia create volatility in international markets

Raising the rate in Dec was designed to contribute to more settled domestic markets, in which investors can be more confident in non-inflationary growth

From 1985 to 1996 Thailand had the fastest increasing economy in the world
- 9% growth per year
- inflation relatively low at 3.4-5.7%

July 1997: Thailand's Tom Yum Kung Crisis
- The currency (bhat) collapses
- 

Malaysia

Indonesia

Ontario teachers and postal workers go on strike

** 1998

Jan 4.5%
Aug 5.5%

In Jan there is a big snow strorm in eastern Canada
- adding to uncertainty

Gordon Thiessen, governor of the BoC argues that a floating exchange rate allows Canada to pursue independent monetary policy in a globalized financial environment
- taxing foreign currency transactions would just increase exchange rate volatility, reduce liquidity, and raise the cost of capital

Prices of commodities are declining
Japanese economy is weak, but US is stronger than expected

Even more pressure weakening the Canadian dollar
- uncertainty in asia led to downward pressure on the prices of commodities that Canada exports to there
- weakening Canadian dollar led to monetary easing
  
Upward pressure on medium/long-term interest rates

US demand for Canadian goods remains strong

*** Problems in Russia

** 1999

** 2000
In Nov they started a new system --- 8 fixed times a year they would announce changes to the interest rate, instead of the old system, in which they could announce changes on any day they felt like
- Feb 5%
- Mar 5.15%
- May 5.75%
- Dec 5.75%

The BoC started worrying about demand pressure in Canada, particularly spilling over from the US, and so decided to raise the policy rate
The worry was the capacity limits

Booming exports from Canada to the US
Lots of spending from Canadian consumers and businesses
Ironically, inflation was relatively low
Energy prices increased rapidly
Growth slowed towards the end of the year, so they held the rate


** 2001

- Jan 5.5%
- Mar 5%
- Apr 4.75%
- May 4.5%
- July 4.25%
- Oct 2.75%
- Nov 2.25%
  
The US economy slowing down, but Canada was staying strong, reaching full capacity
- The US was slowing more than expected, and Canada doing better than expected domestically
- Consequently the Canadian economy was slowing down, but mainly due to the US not importing as much

Generally more uncertainty about whether Canada was going to slow down more or less than expected

And then *9/11* happened
- Economic activity dropped globally
- Uncertainty ran amok
- Consumer and business confidence dropped


** 2002: Huge crash

- Jan 2%
  - Mar 2%
- Apr 2.25%
- June 2.5%
- July 2.75%
  - Sept 2.75%
  - Oct 2.75%
  - Dec 2.75%

Canada had excess supply

Things started to recover in both Canada and the States  by the end of Jan
- Consumer confidence increased, but businesses remained hesitant
  - Later the BoC questioned whether the increase in consumer spending was really due to borrowing from future expenditures

Canada just continued to do much better than expected all throughout the year, so the rate slowly crept higher to compensate
    - It reached production capacity by the end of the year
    - It did better than all other G7 countries
Canadian dollar depreciated

Uncertainty in the middle east by April
- Questions around crude oil prices

Enron collapsed

Lots of global uncertainty and weakening global eonomic activity. The BoC decided to leave the rate unchanged for a while, basically watching and waiting
- Canada's economy started to slow down due to this

By the end of the year, inflation started going up: due to increases in demand for housing, electricity prices in Ontario, and increases in home and auto insurance premiums 



** 2003: Peak

** 2005: Trough

** 2007: Peak

** 2010: Huge crash. We were down to 0.25%

** 2013: Holding steady

** 2015: End of steady

** 2019: Peak

** 2020: Trough

** 2022: Steady

** 2024: Huge jump

** 2025

- Sept 2.5%
- Nov 2.25%
  
Global economic growth is slowing

Canada's GDP shrinks from tariffs
Demand falls
Business investment falls
Housing and consumption up

Weak labour market --- no one wants to hire; unemployment around 7.1% by August

Carney removing retaliatory tariffs helps to ease inflation

In the US business investment confidence is stable, but consumer confidence is dropping

US inflation increases from the tariffs increasing prices

*** October

**** Canadian Survey of Consumer Expectations:

- Canadians want to spend money on Canadian goods and vacations
       + At the same time, they don't want to pay more than an extra 10%
- Hard to find a job, deterioration in the labour market
- Expectation of higher inflation due to tariffs.
- Most consumers expect that the worst effects of the tariffs are still to come, and feel financially unsecure
- However, there are a good chunk of people who think that the most serious effects of the tariffs have been avoided
- Spending intentions rose slightly, in part due to lower gas prices, but /remain weak/ and are mainly concentrated in those who have more wealth (homeowners and older people)
- Economic uncertainty having a big impact on deterring spending
- 2/3 of Canadians *expect a recession* in the next 12 months.
- Number of public sector jobs shrinking due to Carney's government spending cutbacks

**** Business Outlook Survey

- Generally minimal changes in business overall (some feel slightly better, some slightly worse, but no big trend)

- Most businesses don't expect to increase staffing
       + They have enough capacity and have low demand pressures
       + Layoffs occuring in the steel and aluminum industry
       + Wage increase intentions are falling
- Maintenance preferred over expansion, due to soft demand and uncertainty
       + Higher costs of machinery from the US are limiting investment plans
       + Chinese tariffs on canola / agriculture in general restrict investment plans in agriculture
- Expect cost increases due to tariffs and uncertainty
- Most businesses can't pass much of the cost onto consumers due to soft demand
- About 1/3 of businesses expect a recession
- Weak outlook in housing sector
- Low energy prices
- Most businesses actually aren't impacted by tariffs directly, but are rather impacted by consumer sentiment around them: for example, decreased US demand due to the trade friction
       - One of the largest costs on businesses losing money due to tariffs comes from higher steel and aluminum prices affecting imported parts/equipment
- Aluminum being sent to Europe instead of US, but *it's unsustainable* for long-term profitability


*** November
Our productive capacity has lowered due to tariffs
This limits the power of monetary policy to work without heavily increasing inflation

Canada's GDP contracted 1.6% in Q2

**** Fall 2025 Debt Management Strategy Consultations

Hedge funds are becoming increasingly important

