name: Compile and Deploy Digital Garden

on:
  push:
    branches:
      - main                    # Trigger only when you push to main


jobs:
  build-and-deploy:
    runs-on: ubuntu-latest      # Github's cloud OS

    steps:
      - name: Checkout local repository
        uses: actions/checkout@v4

      - name: Pre-populate output target from gh-pages branch
        uses: actions/checkout@v4
        continue-on-error: true
        with:
          ref: gh-pages
          path: ./public-export

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y emacs-nox pandoc

      - name: Execute Local Compilation Toolchain
        run: |
          make                  # Runs the GNU Makefile
      - name: Deploy Compiled Artifacts to Github Pages Branch
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{  secrets.GITHUB_TOKEN}}
          publish_dir: ./public-export
          publish_branch: gh-pages
